import{MAP}from'../data/map.js';import{TOWERS}from'../data/towers.js';import{WAVES,waveEnemyCount}from'../data/waves.js';import{Enemy}from'../entities/Enemy.js';import{Tower}from'../entities/Tower.js';import{Projectile}from'../entities/Projectile.js';import{HUD}from'../ui/HUD.js';
export class Game{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.canvas.width=MAP.worldW;this.canvas.height=MAP.worldH;this.hud=new HUD(this);this.sound=true;this.speed=1;this.paused=false;this.bind();this.reset();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
 reset(){this.phase='intro';this.gold=600;this.baseHp=100;this.waveIndex=0;this.waveTotal=waveEnemyCount(0);this.waveDefeated=0;this.spawnQueue=[];this.spawnClock=0;this.enemies=[];this.enemyPool=[];this.towers=[];this.projectiles=[];this.particles=[];this.floaters=[];this.selectedPad=null;this.pads=MAP.pads.map((p,i)=>({...p,id:i,tower:null}));this.hud.render()}
 bind(){document.querySelector('#play').onclick=()=>{document.querySelector('#intro').classList.add('hidden');this.phase='build';this.hud.toast('BUILD YOUR DEFENSE');this.hud.render()};this.hud.start.onclick=()=>this.startWave();document.querySelector('#pause').onclick=()=>{this.paused=!this.paused;this.hud.toast(this.paused?'PAUSED':'RESUMED')};document.querySelector('#speed').onclick=e=>{this.speed=this.speed===1?2:1;e.currentTarget.textContent=this.speed+'×'};document.querySelector('#sound').onclick=e=>{this.sound=!this.sound;e.currentTarget.textContent=this.sound?'♪':'×'};this.canvas.addEventListener('pointerdown',e=>{e.preventDefault();this.tap(e)});addEventListener('resize',()=>this.fit());this.fit()}
 fit(){const ratio=MAP.worldW/MAP.worldH,w=innerWidth,h=innerHeight;this.canvas.style.width=(w/h<ratio?w:h*ratio)+'px';this.canvas.style.height=(w/h<ratio?w/ratio:h)+'px'}
 pointer(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*MAP.worldW/r.width,y:(e.clientY-r.top)*MAP.worldH/r.height}}
 tap(e){if(this.phase==='intro'||this.paused)return;const p=this.pointer(e),pad=this.pads.find(q=>Math.hypot(q.x-p.x,q.y-p.y)<58);if(!pad){this.hud.closeMenu();return}this.selectedPad=pad;if(!pad.tower)this.openBuildMenu(pad);else this.openUpgradeMenu(pad)}
 openBuildMenu(pad){const m=this.hud.menu;m.classList.remove('hidden');m.innerHTML=Object.entries(TOWERS).map(([key,t])=>`<button data-build="${key}" ${this.gold<t.cost?'disabled':''}>${t.name}<small>● ${t.cost}</small></button>`).join('')+`<button class="close wide">CLOSE</button>`;m.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>this.build(pad,b.dataset.build));m.querySelector('.close').onclick=()=>this.hud.closeMenu()}
 openUpgradeMenu(pad){const t=pad.tower,m=this.hud.menu,cost=t.upgradeCost;m.classList.remove('hidden');m.innerHTML=`<button class="wide" disabled>${t.label} · LEVEL ${t.level}<small>DMG ${Math.round(t.stats.damage)} · RNG ${Math.round(t.stats.range)}</small></button>${t.level<4?`<button class="upgrade wide" data-up ${this.gold<cost?'disabled':''}>UPGRADE — ${cost}</button>`:`<button class="wide" disabled>MAX LEVEL</button>`}<button class="close wide">CLOSE</button>`;m.querySelector('[data-up]')?.addEventListener('click',()=>this.upgrade(pad));m.querySelector('.close').onclick=()=>this.hud.closeMenu()}
 build(pad,type){const cost=TOWERS[type].cost;if(pad.tower||this.gold<cost)return;this.gold-=cost;pad.tower=new Tower(type,pad.x,pad.y);this.towers.push(pad.tower);this.burst(pad.x,pad.y,TOWERS[type].color,18);this.hud.toast(`${TOWERS[type].name} ONLINE`);this.hud.closeMenu();this.hud.render()}
 upgrade(pad){const t=pad.tower,cost=t.upgradeCost;if(!cost||this.gold<cost)return;this.gold-=cost;t.level++;this.burst(t.x,t.y,'#ffe16a',24);this.hud.toast(`LEVEL ${t.level}!`);this.openUpgradeMenu(pad);this.hud.render()}
 startWave(){if(this.phase!=='build'||this.waveIndex>=WAVES.length)return;this.phase='wave';this.hud.closeMenu();this.spawnQueue=[];let time=.8;for(const group of WAVES[this.waveIndex].groups){time+=group.gap||0;for(let i=0;i<group.count;i++){this.spawnQueue.push({time,type:group.type});time+=group.interval}time+=.55}this.spawnClock=0;this.waveTotal=waveEnemyCount(this.waveIndex);this.waveDefeated=0;this.hud.toast(`WAVE ${this.waveIndex+1}`);this.hud.render()}
 spawn(type){const e=this.enemyPool.pop()||new Enemy(type,MAP.path);e.reset(type,MAP.path);e.x+=Math.random()*12-6;e.y+=Math.random()*12-6;this.enemies.push(e)}
 kill(e){if(!e.active)return;e.active=false;this.gold+=e.reward;this.waveDefeated++;this.floaters.push({x:e.x,y:e.y,text:`+${e.reward}`,life:1,color:'#ffd43b'});this.burst(e.x,e.y,e.color,7);this.enemyPool.push(e)}
 leak(e){e.active=false;this.baseHp=Math.max(0,this.baseHp-e.damage);this.enemyPool.push(e);this.burst(MAP.base.x,MAP.base.y,'#ff684f',12);if(this.baseHp<=0){this.phase='lost';this.hud.start.classList.add('hidden');this.hud.toast('BASE LOST — TAP RELOAD TO TRY AGAIN',5000)}}
 fire(t,target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);t.fired();this.projectiles.push(new Projectile(t.x+Math.cos(t.angle)*22,t.y+Math.sin(t.angle)*22,target,t.stats,t.type));this.burst(t.x+Math.cos(t.angle)*26,t.y+Math.sin(t.angle)*26,t.stats.color,3)}
 hit(p){if(p.splash){for(const e of this.enemies)if(e.active&&Math.hypot(e.x-p.x,e.y-p.y)<=p.splash){e.hp-=p.damage;if(e.hp<=0)this.kill(e)}}else if(p.target?.active){p.target.hp-=p.damage;if(p.slow){p.target.slow=Math.max(p.target.slow,p.slow);p.target.slowTime=2.2}if(p.target.hp<=0)this.kill(p.target)}this.burst(p.x,p.y,p.color,p.type==='cannon'?12:5)}
 update(dt){if(this.phase!=='wave'||this.paused)return;dt*=this.speed;this.spawnClock+=dt;while(this.spawnQueue.length&&this.spawnQueue[0].time<=this.spawnClock){this.spawn(this.spawnQueue.shift().type)}for(const e of this.enemies)if(e.active&&e.update(dt))this.leak(e);for(const t of this.towers){t.update(dt);if(!t.canFire())continue;let target=null,best=-1;for(const e of this.enemies){if(!e.active)continue;const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<=t.stats.range){const progress=e.segment;if(progress>best){best=progress;target=e}}}if(target)this.fire(t,target)}for(const p of this.projectiles)if(p.active&&p.update(dt)){this.hit(p);p.active=false}this.projectiles=this.projectiles.filter(p=>p.active);this.enemies=this.enemies.filter(e=>e.active);for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.96;q.vy*=.96}this.particles=this.particles.filter(q=>q.life>0);for(const f of this.floaters){f.life-=dt;f.y-=28*dt}this.floaters=this.floaters.filter(f=>f.life>0);if(!this.spawnQueue.length&&!this.enemies.length&&this.phase==='wave')this.clearWave();this.hud.render()}
 clearWave(){const bonus=WAVES[this.waveIndex].bonus;this.gold+=bonus;this.floaters.push({x:360,y:560,text:`WAVE CLEAR +${bonus}`,life:2,color:'#ffe45c'});this.waveIndex++;if(this.waveIndex>=WAVES.length){this.phase='won';this.hud.toast('DUSTWALL SAVED!',5000);this.hud.start.classList.add('hidden');return}this.phase='build';this.waveTotal=waveEnemyCount(this.waveIndex);this.waveDefeated=0;this.hud.toast(`WAVE CLEARED · +${bonus} GOLD`,2500);this.hud.render()}
 burst(x,y,color,n){for(let i=0;i<n&&this.particles.length<260;i++){const a=Math.random()*Math.PI*2,s=20+Math.random()*70;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,color,size:2+Math.random()*3})}}
 loop(t){const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;this.update(dt);this.draw();requestAnimationFrame(n=>this.loop(n))}
 draw(){const c=this.ctx;c.fillStyle='#c9894f';c.fillRect(0,0,720,1120);this.drawWorld(c);for(const e of this.enemies)if(e.active)this.drawEnemy(c,e);for(const p of this.projectiles)if(p.active){c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.type==='cannon'?6:3,0,Math.PI*2);c.fill()}for(const t of this.towers)this.drawTower(c,t);for(const pad of this.pads)if(!pad.tower)this.drawPad(c,pad);for(const q of this.particles){c.globalAlpha=Math.max(0,q.life*2);c.fillStyle=q.color;c.fillRect(q.x-q.size/2,q.y-q.size/2,q.size,q.size)}c.globalAlpha=1;for(const f of this.floaters){c.globalAlpha=Math.min(1,f.life*2);c.fillStyle=f.color;c.font='bold 20px Arial';c.textAlign='center';c.strokeStyle='#000';c.lineWidth=4;c.strokeText(f.text,f.x,f.y);c.fillText(f.text,f.x,f.y)}c.globalAlpha=1}
 drawWorld(c){c.fillStyle='#d89a5d';for(let i=0;i<35;i++){const x=(i*149)%720,y=(i*263)%1120;c.fillRect(x,y,4,2)}c.strokeStyle='#6e685f';c.lineWidth=34;c.lineJoin='round';c.lineCap='round';c.beginPath();MAP.path.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();c.strokeStyle='#b6a58b';c.lineWidth=22;c.stroke();c.strokeStyle='#4f4a45';c.lineWidth=3;c.setLineDash([12,18]);c.stroke();c.setLineDash([]);c.save();c.translate(MAP.base.x,MAP.base.y);c.fillStyle='#0c467a';c.strokeStyle='#8dd6ff';c.lineWidth=7;c.beginPath();c.arc(0,0,74,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#e7f0f5';c.fillRect(-42,-36,84,72);c.fillStyle='#3d8fd0';c.fillRect(-30,-23,60,46);c.fillStyle='#162a3a';c.fillRect(-15,-10,30,20);c.restore();for(const [x,y] of [[45,1050],[665,1030],[70,330]])this.drawPalm(c,x,y)}
 drawPalm(c,x,y){c.save();c.translate(x,y);c.strokeStyle='#714a27';c.lineWidth=9;c.beginPath();c.moveTo(0,42);c.quadraticCurveTo(-5,8,5,-30);c.stroke();c.strokeStyle='#5f7f32';c.lineWidth=7;for(let i=0;i<6;i++){const a=i*Math.PI/3;c.beginPath();c.moveTo(5,-30);c.lineTo(5+Math.cos(a)*38,-30+Math.sin(a)*24);c.stroke()}c.restore()}
 drawPad(c,p){c.save();c.translate(p.x,p.y);c.fillStyle='#24445f';c.strokeStyle='#7fd0ff';c.lineWidth=4;c.beginPath();c.arc(0,0,28,0,Math.PI*2);c.fill();c.stroke();const price=TOWERS[p.type].cost;c.fillStyle='#1879bf';c.strokeStyle='#0b2e4d';c.lineWidth=3;c.beginPath();c.roundRect(-35,-66,70,38,8);c.fill();c.stroke();c.fillStyle='#ffd22d';c.beginPath();c.arc(-19,-47,9,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='bold 18px Arial';c.textAlign='center';c.strokeStyle='#000';c.lineWidth=4;c.strokeText(price,8,-41);c.fillText(price,8,-41);c.restore()}
 drawTower(c,t){const s=t.stats;c.save();c.translate(t.x,t.y);c.fillStyle='#edf5f8';c.strokeStyle=s.accent;c.lineWidth=5;c.beginPath();c.arc(0,0,25+t.level*2,0,Math.PI*2);c.fill();c.stroke();c.rotate(t.angle);c.fillStyle=s.accent;c.fillRect(-7,-8,28+t.level*3,16);if(t.type==='cannon'){c.fillStyle='#526777';c.fillRect(7,-11,25,22)}if(t.type==='freeze'){c.fillStyle='#aef8ff';c.beginPath();c.arc(6,0,11,0,Math.PI*2);c.fill()}c.restore();c.fillStyle='#fff';c.font='bold 11px Arial';c.textAlign='center';c.fillText(`L${t.level}`,t.x,t.y+43)}
 drawEnemy(c,e){c.save();c.translate(e.x,e.y);c.rotate(e.angle);c.fillStyle='#1d2b27';c.fillRect(-e.size*.7,e.size*.45,e.size*.45,e.size*.75);c.fillRect(e.size*.2,e.size*.45,e.size*.45,e.size*.75);c.fillStyle=e.color;c.beginPath();c.arc(0,0,e.size,0,Math.PI*2);c.fill();c.fillStyle='#173d25';c.beginPath();c.arc(1,-e.size*.35,e.size*.82,Math.PI,0);c.fill();c.fillStyle='#dff7d8';c.fillRect(e.size*.3,-2,3,3);c.restore();if(e.hp<e.maxHp){c.fillStyle='#18201c';c.fillRect(e.x-13,e.y-e.size-9,26,4);c.fillStyle='#58e65f';c.fillRect(e.x-13,e.y-e.size-9,26*Math.max(0,e.hp/e.maxHp),4)}}
}
