(()=>{
const sector=window.FUN_TD_SECTOR||1,$=s=>document.querySelector(s),game=$('#game');if(!game)return;
const fx=document.createElement('canvas');fx.id='fxCanvas';fx.width=720;fx.height=1120;game.insertAdjacentElement('afterend',fx);const c=fx.getContext('2d');
const flash=document.createElement('div');flash.className='screen-flash';document.body.appendChild(flash);
const boss=document.createElement('div');boss.id='bossHud';boss.innerHTML='<small>BOSS CONTACT</small><strong>THREAT DETECTED</strong><span class="boss-phase">INBOUND</span>';document.body.appendChild(boss);
const chip=document.createElement('div');chip.className='audio-chip';chip.textContent='AUDIO ARMED';document.body.appendChild(chip);
const themes={1:{p:'#d7a261',p2:'#f4d28f',kind:'dust',root:55},2:{p:'#d9f5ff',p2:'#8ddcff',kind:'snow',root:62},3:{p:'#ff8b5e',p2:'#ffcc64',kind:'ash',root:49},4:{p:'#6ee9ff',p2:'#9cdfff',kind:'rain',root:46},5:{p:'#a78cff',p2:'#e9b7ff',kind:'spark',root:41},6:{p:'#cf82ff',p2:'#6ae8ff',kind:'null',root:37}},theme=themes[sector]||themes[1];
let particles=[],last=performance.now(),shake=0;
function fit(){const r=game.getBoundingClientRect();fx.style.width=r.width+'px';fx.style.height=r.height+'px';fx.style.left=(r.left+r.width/2)+'px';fx.style.top=(r.top+r.height/2)+'px'}addEventListener('resize',fit);requestAnimationFrame(fit);
function spawnAmbient(){const k=theme.kind;if(k==='snow')particles.push({x:Math.random()*720,y:-10,vx:-6+Math.random()*12,vy:18+Math.random()*30,s:1+Math.random()*3,a:.3+Math.random()*.5});else if(k==='rain')particles.push({x:Math.random()*760,y:-20,vx:-18,vy:260+Math.random()*140,s:10+Math.random()*18,a:.18+Math.random()*.24});else if(k==='ash')particles.push({x:Math.random()*720,y:1140,vx:-8+Math.random()*16,vy:-15-Math.random()*28,s:1+Math.random()*3,a:.2+Math.random()*.35});else if(k==='dust')particles.push({x:-10,y:200+Math.random()*800,vx:20+Math.random()*35,vy:-3+Math.random()*6,s:2+Math.random()*5,a:.08+Math.random()*.13});else if(k==='spark'||k==='null')particles.push({x:Math.random()*720,y:150+Math.random()*900,vx:-5+Math.random()*10,vy:-10-Math.random()*20,s:1+Math.random()*2,a:.15+Math.random()*.35});if(particles.length>95)particles.splice(0,particles.length-95)}
function drawPads(){if(sector!==6)return;const pads=[[620,205],[385,175],[105,335],[390,340],[645,490],[495,650],[245,585],[245,805],[470,815],[620,900],[110,1040],[370,1010]];c.save();for(const [x,y] of pads){const g=c.createRadialGradient(x,y,12,x,y,43);g.addColorStop(0,'#6eeeff12');g.addColorStop(.55,'#6eeeff0d');g.addColorStop(1,'transparent');c.fillStyle=g;c.beginPath();c.arc(x,y,43,0,Math.PI*2);c.fill();c.strokeStyle='#76eaff28';c.lineWidth=1.5;c.beginPath();c.arc(x,y,36+Math.sin(performance.now()/500+x)*2,0,Math.PI*2);c.stroke()}c.restore()}
function drawNull(){if(sector!==6)return;c.save();c.globalCompositeOperation='screen';c.strokeStyle='#9c7bff12';c.lineWidth=1;for(let y=140;y<1060;y+=72){c.beginPath();c.moveTo(0,y);c.lineTo(720,y);c.stroke()}for(let x=20;x<720;x+=90){c.beginPath();c.moveTo(x,120);c.lineTo(x,1080);c.stroke()}c.fillStyle='#c980ff0b';for(let i=0;i<7;i++){const x=(i*137+performance.now()*.015)%780-30;c.fillRect(x,120,2,930)}c.restore()}
function frame(t){const dt=Math.min(.04,(t-last)/1000);last=t;if(Math.random()<dt*(theme.kind==='rain'?34:9))spawnAmbient();c.clearRect(0,0,720,1120);drawNull();drawPads();c.save();c.globalCompositeOperation='screen';for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.a-=dt*(theme.kind==='rain' ? .08 : .03);c.globalAlpha=Math.max(0,p.a);c.strokeStyle=theme.p;c.fillStyle=theme.p;if(theme.kind==='rain'){c.lineWidth=1.2;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x+p.vx*.05,p.y+p.s);c.stroke()}else{c.beginPath();c.arc(p.x,p.y,p.s,0,Math.PI*2);c.fill()}}c.restore();particles=particles.filter(p=>p.a>0&&p.y<1160&&p.y>-40&&p.x>-60&&p.x<780);if(shake>0)shake=Math.max(0,shake-dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
function hitFlash(type='hit'){flash.className='screen-flash';void flash.offsetWidth;flash.classList.add(type);if(type==='boss')shake=.4}
let ctx=null,master=null,music=null,sfx=null,muted=localStorage.getItem('funTD_audioMuted')==='1',pulseTimer=null;function ensure(){if(ctx)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;ctx=new A();master=ctx.createGain();music=ctx.createGain();sfx=ctx.createGain();music.gain.value=.18;sfx.gain.value=.48;music.connect(master);sfx.connect(master);master.connect(ctx.destination);master.gain.value=muted?0:1;startAmbience()}
function osc(freq,dur=.08,type='square',vol=.04,dest=sfx,slide=0){if(!ctx||muted)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,ctx.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,freq+slide),ctx.currentTime+dur);g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+dur);o.connect(g);g.connect(dest);o.start();o.stop(ctx.currentTime+dur)}
function noise(dur=.08,vol=.03,filter=1600){if(!ctx||muted)return;const b=ctx.createBuffer(1,Math.max(1,ctx.sampleRate*dur),ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=filter;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+dur);s.connect(f);f.connect(g);g.connect(sfx);s.start()}
function sfxClick(){osc(420,.035,'square',.025)}function sfxBuild(){osc(180,.08,'square',.05,sfx,140);setTimeout(()=>osc(360,.06,'triangle',.035),45)}function sfxUpgrade(){osc(280,.08,'triangle',.05,sfx,180);setTimeout(()=>osc(520,.11,'triangle',.04,sfx,180),70)}function sfxKill(){osc(680,.035,'square',.018);if(Math.random()<.3)osc(980,.025,'sine',.012)}function sfxWave(){osc(theme.root*4,.12,'sawtooth',.05,sfx,theme.root*5);setTimeout(()=>osc(theme.root*6,.16,'triangle',.045),110)}function sfxBoss(){noise(.4,.08,600);osc(theme.root*2,.45,'sawtooth',.08,sfx,-theme.root*.8);setTimeout(()=>osc(theme.root*3,.32,'square',.045),180)}function sfxWin(){[392,494,587,784].forEach((f,i)=>setTimeout(()=>osc(f,.22,'triangle',.045),i*110))}function sfxLose(){osc(170,.5,'sawtooth',.06,sfx,-80);noise(.28,.05,500)}
function startAmbience(){if(!ctx)return;const root=theme.root,drone=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();drone.type=sector>=5?'sawtooth':'triangle';drone.frequency.value=root;f.type='lowpass';f.frequency.value=sector>=5?420:260;g.gain.value=.018;drone.connect(f);f.connect(g);g.connect(music);drone.start();pulseTimer=setInterval(()=>{if(!ctx||muted)return;osc(root*(sector>=5?2:1.5),.2,'sine',.012,music,root*.2)},sector===4?1800:sector>=5?2200:2800)}
function toggle(){ensure();muted=!muted;localStorage.setItem('funTD_audioMuted',muted?'1':'0');if(master)master.gain.setTargetAtTime(muted?0:1,ctx.currentTime,.03);document.body.classList.toggle('audio-muted',muted);const b=$('#sound');if(b){b.textContent=muted?'×':'♪';b.classList.toggle('audio-on',!muted)}chip.textContent=muted?'AUDIO MUTED':'AUDIO ON'}
document.body.classList.toggle('audio-muted',muted);addEventListener('pointerdown',()=>{ensure();if(ctx?.state==='suspended')ctx.resume()},{once:true});const sound=$('#sound');if(sound){sound.textContent=muted?'×':'♪';sound.classList.toggle('audio-on',!muted);sound.addEventListener('click',e=>{e.stopPropagation();toggle()})}
document.addEventListener('click',e=>{ensure();const b=e.target.closest?.('button');if(!b||b.id==='sound')return;sfxClick();if(b.matches('[data-build]')){setTimeout(sfxBuild,30);hitFlash('wave')}if(b.matches('[data-up]')){setTimeout(sfxUpgrade,30);hitFlash('wave')}if(b.id==='startWave'){sfxWave();hitFlash('wave')}});
const progress=$('#progressText');if(progress){let lastN=0;new MutationObserver(()=>{const n=parseInt((progress.textContent||'0').split('/')[0],10)||0;if(n>lastN){const diff=Math.min(4,n-lastN);for(let i=0;i<diff;i++)setTimeout(sfxKill,i*18);if(n-lastN>4)osc(860,.05,'triangle',.025);if(n%10===0)hitFlash('hit')}lastN=n}).observe(progress,{childList:true,subtree:true,characterData:true})}
const wave=$('#wave'),names={1:'SAND TITAN',2:'ICE TITAN',3:'MAGMA COLOSSUS',4:'STORM LEVIATHAN',5:'ECLIPSE ENGINE',6:'THE OVERSEER'};/* The boss banner is a contact alert, not a label. It used to hide only when the wave number changed, and on the final wave that number never changes again - so it sat over the battlefield for the whole fight and through the victory screen. It now dismisses itself, and any overlay takes it down early. */let bossTimer=0,bossShownFor=0;function hideBoss(){clearTimeout(bossTimer);boss.classList.remove('show')}function bossState(){const w=parseInt(wave?.textContent||'1',10)||1;if(w!==20){bossShownFor=0;hideBoss();return}if(bossShownFor===w)return;bossShownFor=w;boss.querySelector('strong').textContent=names[sector]||'BOSS';boss.querySelector('.boss-phase').textContent=sector===6?'PHASE I · COMMAND CORE':'FINAL WAVE';boss.classList.add('show');clearTimeout(bossTimer);bossTimer=setTimeout(hideBoss,4200)}if(wave){new MutationObserver(bossState).observe(wave,{childList:true,subtree:true,characterData:true});bossState()}const flow=document.getElementById('gameFlowOverlay');if(flow)new MutationObserver(()=>{if(flow.classList.contains('show'))hideBoss()}).observe(flow,{attributes:true,attributeFilter:['class']});
const toast=$('#toast');if(toast)new MutationObserver(()=>{const t=(toast.textContent||'').toUpperCase();if(!t)return;if(t.includes('PHASE II')){boss.classList.add('show');boss.querySelector('.boss-phase').textContent='PHASE II · FORTRESS SHIELD';sfxBoss();hitFlash('boss')}else if(t.includes('PHASE III')){boss.classList.add('show');boss.querySelector('.boss-phase').textContent='PHASE III · OVERDRIVE';sfxBoss();hitFlash('boss')}else if(t.includes('BOSS')||t.includes('OVERSEER')||t.includes('LEVIATHAN')||t.includes('ECLIPSE')){sfxBoss();hitFlash('boss')}else if(t.includes('WAVE CLEARED')){osc(740,.09,'triangle',.035);setTimeout(()=>osc(990,.12,'triangle',.03),80)}else if(t.includes('BASE LOST'))sfxLose();else if(t.includes('SAVED')||t.includes('LINE HELD')||t.includes('OFFLINE'))sfxWin()}).observe(toast,{childList:true,subtree:true,characterData:true});const intel=$('#waveIntel');if(intel)new MutationObserver(()=>{if((intel.textContent||'').toUpperCase().includes('WAVE 20')){bossState();hitFlash('boss')}}).observe(intel,{childList:true,subtree:true,characterData:true});
})();