(()=>{
const MAP={worldW:720,worldH:1120,base:{x:108,y:555,r:72},path:[[705,155],[535,155],[535,300],[655,300],[655,470],[420,470],[420,675],[625,675],[625,890],[340,890],[340,735],[220,735],[220,600],[150,600]],pads:[{x:430,y:230,type:'gun'},{x:620,y:220,type:'cannon'},{x:470,y:385,type:'gun'},{x:565,y:550,type:'freeze'},{x:330,y:565,type:'cannon'},{x:515,y:775,type:'gun'},{x:255,y:825,type:'freeze'},{x:485,y:985,type:'cannon'},{x:205,y:960,type:'gun'},{x:110,y:700,type:'gun'}]};
const TOWERS={gun:{name:'GUN TOWER',cost:100,damage:18,rate:4.5,range:155,projectileSpeed:720,color:'#56c5ff',accent:'#1b78cf'},cannon:{name:'CANNON',cost:200,damage:55,rate:.9,range:190,projectileSpeed:330,splash:55,color:'#ffb24b',accent:'#df6f22'},freeze:{name:'FREEZE',cost:150,damage:8,rate:1.8,range:160,projectileSpeed:560,slow:.30,color:'#8cf5ff',accent:'#2ca7d9'}};
const ENEMIES={grunt:{hp:34,speed:54,reward:5,damage:1,size:10,color:'#36d058'},scout:{hp:27,speed:76,reward:7,damage:1,size:8,color:'#79ee55'},armored:{hp:105,speed:40,reward:12,damage:2,size:12,color:'#23934a'},heavy:{hp:280,speed:28,reward:20,damage:5,size:17,color:'#18743f'},boss:{hp:2300,speed:20,reward:250,damage:15,size:30,color:'#0e5938'}};
const g=(type,count,interval=.42,gap=0)=>({type,count,interval,gap});
const WAVES=[[g('grunt',8,.68)],[g('grunt',12,.62)],[g('grunt',16,.58)],[g('grunt',22,.54)],[g('grunt',28,.50)],[g('grunt',20,.46),g('scout',8,.52,1.2)],[g('grunt',26,.44),g('scout',10,.48,1.1)],[g('grunt',30,.42),g('armored',6,.66,1.1)],[g('grunt',36,.40),g('scout',14,.44,1)],[g('grunt',42,.38),g('armored',8,.60,1)],[g('grunt',48,.36),g('scout',16,.40,.9)],[g('grunt',55,.35),g('armored',10,.56,.9)],[g('grunt',60,.34),g('heavy',4,.9,1)],[g('grunt',66,.33),g('scout',20,.38,.8),g('armored',8,.52,.8)],[g('grunt',72,.32),g('heavy',5,.82,.8)],[g('grunt',82,.30),g('scout',22,.34,.8)],[g('grunt',90,.29),g('armored',14,.48,.7)],[g('grunt',100,.28),g('heavy',7,.75,.7)],[g('grunt',110,.27),g('scout',28,.32,.7),g('armored',16,.46,.7)],[g('boss',1,1),g('grunt',90,.29,1.5),g('heavy',8,.72,.8)]].map((groups,i)=>({groups,bonus:75+i*10}));
const countWave=i=>WAVES[i]?WAVES[i].groups.reduce((n,x)=>n+x.count,0):0;
const towerStats=(type,level)=>{const b=TOWERS[type],n=level-1;return{...b,damage:b.damage*(1+n*.55),rate:b.rate*(1+n*.16),range:b.range*(1+n*.07),splash:b.splash?b.splash+n*8:0,slow:b.slow?Math.min(.55,b.slow+n*.07):0}};
const upgradeCost=(type,level)=>level<4?Math.round([0,1,2,4][level]*TOWERS[type].cost):0;
class Enemy{constructor(type){this.reset(type)}reset(type){const d=ENEMIES[type];Object.assign(this,d);this.type=type;this.maxHp=d.hp;this.hp=d.hp;this.segment=0;this.x=MAP.path[0][0];this.y=MAP.path[0][1];this.slow=0;this.slowTime=0;this.active=true;this.angle=0;return this}update(dt){if(this.slowTime>0)this.slowTime-=dt;else this.slow=0;let travel=this.speed*(1-this.slow)*dt;while(travel>0&&this.segment<MAP.path.length-1){const b=MAP.path[this.segment+1],dx=b[0]-this.x,dy=b[1]-this.y,d=Math.hypot(dx,dy);this.angle=Math.atan2(dy,dx);if(travel>=d){this.x=b[0];this.y=b[1];this.segment++;travel-=d}else{this.x+=dx/d*travel;this.y+=dy/d*travel;travel=0}}return this.segment>=MAP.path.length-1}}
class Tower{constructor(type,x,y){this.type=type;this.x=x;this.y=y;this.level=1;this.cooldown=0;this.angle=-Math.PI/2}get stats(){return towerStats(this.type,this.level)}update(dt){this.cooldown-=dt}canFire(){return this.cooldown<=0}fired(){this.cooldown=1/this.stats.rate}}
class Projectile{constructor(x,y,target,stats,type){this.x=x;this.y=y;this.target=target;this.speed=stats.projectileSpeed;this.damage=stats.damage;this.splash=stats.splash||0;this.slow=stats.slow||0;this.type=type;this.color=stats.color;this.active=true}update(dt){if(!this.active||!this.target||!this.target.active){this.active=false;return false}const dx=this.target.x-this.x,dy=this.target.y-this.y,d=Math.hypot(dx,dy),step=this.speed*dt;if(d<=step+7){this.x=this.target.x;this.y=this.target.y;return true}this.x+=dx/d*step;this.y+=dy/d*step;return false}}
class Game{constructor(){this.canvas=document.getElementById('game');this.ctx=this.canvas.getContext('2d');this.canvas.width=720;this.canvas.height=1120;this.goldEl=document.getElementById('gold');this.waveEl=document.getElementById('wave');this.hpEl=document.getElementById('hp');this.fill=document.getElementById('progressFill');this.progress=document.getElementById('progressText');this.start=document.getElementById('startWave');this.menu=document.getElementById('towerMenu');this.toastEl=document.getElementById('toast');this.reset();this.bind();this.fit();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
reset(){this.phase='intro';this.gold=600;this.baseHp=100;this.waveIndex=0;this.waveTotal=countWave(0);this.waveDefeated=0;this.spawnQueue=[];this.spawnClock=0;this.enemies=[];this.towers=[];this.projectiles=[];this.particles=[];this.floaters=[];this.speed=1;this.paused=false;this.pads=MAP.pads.map((p,i)=>({...p,id:i,tower:null}));this.renderHud()}
bind(){document.getElementById('play').onclick=()=>{document.getElementById('intro').classList.add('hidden');this.phase='build';this.toast('BUILD YOUR DEFENSE');this.renderHud()};this.start.onclick=()=>this.startWave();document.getElementById('pause').onclick=()=>{this.paused=!this.paused;this.toast(this.paused?'PAUSED':'RESUMED')};document.getElementById('speed').onclick=e=>{this.speed=this.speed===1?2:1;e.currentTarget.textContent=this.speed+'×'};document.getElementById('sound').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♪'?'×':'♪'};this.canvas.addEventListener('pointerdown',e=>{e.preventDefault();this.tap(e)});addEventListener('resize',()=>this.fit())}
fit(){const ratio=720/1120,w=innerWidth,h=innerHeight;this.canvas.style.width=(w/h<ratio?w:h*ratio)+'px';this.canvas.style.height=(w/h<ratio?w/ratio:h)+'px'}
renderHud(){this.goldEl.textContent=Math.floor(this.gold);this.waveEl.textContent=Math.min(20,this.waveIndex+1);this.hpEl.textContent=this.baseHp;this.progress.textContent=`${this.waveDefeated} / ${this.waveTotal}`;this.fill.style.width=(this.waveTotal?Math.min(100,this.waveDefeated/this.waveTotal*100):0)+'%';this.start.textContent=`START WAVE ${Math.min(20,this.waveIndex+1)}`;this.start.classList.toggle('hidden',this.phase!=='build')}
toast(msg,time=1800){clearTimeout(this.toastTimer);this.toastEl.textContent=msg;this.toastEl.classList.add('show');this.toastTimer=setTimeout(()=>this.toastEl.classList.remove('show'),time)}
closeMenu(){this.menu.classList.add('hidden');this.menu.innerHTML=''}
pointer(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*1120/r.height}}
tap(e){if(this.phase==='intro'||this.paused)return;const p=this.pointer(e),pad=this.pads.find(q=>Math.hypot(q.x-p.x,q.y-p.y)<62);if(!pad){this.closeMenu();return}pad.tower?this.upgradeMenu(pad):this.buildMenu(pad)}
buildMenu(pad){this.menu.classList.remove('hidden');this.menu.innerHTML=Object.entries(TOWERS).map(([k,t])=>`<button data-build="${k}" ${this.gold<t.cost?'disabled':''}>${t.name}<small>● ${t.cost}</small></button>`).join('')+'<button class="close wide">CLOSE</button>';this.menu.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>this.build(pad,b.dataset.build));this.menu.querySelector('.close').onclick=()=>this.closeMenu()}
upgradeMenu(pad){const t=pad.tower,cost=upgradeCost(t.type,t.level),s=t.stats;this.menu.classList.remove('hidden');this.menu.innerHTML=`<button class="wide" disabled>${TOWERS[t.type].name} · LEVEL ${t.level}<small>DMG ${Math.round(s.damage)} · RNG ${Math.round(s.range)}</small></button>${t.level<4?`<button class="upgrade wide" data-up ${this.gold<cost?'disabled':''}>UPGRADE — ${cost}</button>`:'<button class="wide" disabled>MAX LEVEL</button>'}<button class="close wide">CLOSE</button>`;const up=this.menu.querySelector('[data-up]');if(up)up.onclick=()=>this.upgrade(pad);this.menu.querySelector('.close').onclick=()=>this.closeMenu()}
build(pad,type){const cost=TOWERS[type].cost;if(pad.tower||this.gold<cost)return;this.gold-=cost;pad.tower=new Tower(type,pad.x,pad.y);this.towers.push(pad.tower);this.burst(pad.x,pad.y,TOWERS[type].color,15);this.closeMenu();this.renderHud()}
upgrade(pad){const t=pad.tower,cost=upgradeCost(t.type,t.level);if(!cost||this.gold<cost)return;this.gold-=cost;t.level++;this.burst(t.x,t.y,'#ffe16a',22);this.upgradeMenu(pad);this.renderHud()}
startWave(){if(this.phase!=='build')return;this.phase='wave';this.closeMenu();this.spawnQueue=[];let time=.8;for(const group of WAVES[this.waveIndex].groups){time+=group.gap||0;for(let i=0;i<group.count;i++){this.spawnQueue.push({time,type:group.type});time+=group.interval}time+=.55}this.spawnClock=0;this.waveTotal=countWave(this.waveIndex);this.waveDefeated=0;this.toast(`WAVE ${this.waveIndex+1}`);this.renderHud()}
spawn(type){const e=new Enemy(type);e.x+=Math.random()*10-5;e.y+=Math.random()*10-5;this.enemies.push(e)}
kill(e){if(!e.active)return;e.active=false;this.gold+=e.reward;this.waveDefeated++;this.floaters.push({x:e.x,y:e.y,text:`+${e.reward}`,life:1,color:'#ffd43b'});this.burst(e.x,e.y,e.color,7)}
leak(e){e.active=false;this.baseHp=Math.max(0,this.baseHp-e.damage);if(this.baseHp<=0){this.phase='lost';this.start.classList.add('hidden');this.toast('BASE LOST',4000)}}
fire(t,target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);t.fired();this.projectiles.push(new Projectile(t.x+Math.cos(t.angle)*22,t.y+Math.sin(t.angle)*22,target,t.stats,t.type))}
hit(p){if(p.splash){for(const e of this.enemies)if(e.active&&Math.hypot(e.x-p.x,e.y-p.y)<=p.splash){e.hp-=p.damage;if(e.hp<=0)this.kill(e)}}else if(p.target&&p.target.active){p.target.hp-=p.damage;if(p.slow){p.target.slow=Math.max(p.target.slow,p.slow);p.target.slowTime=2.2}if(p.target.hp<=0)this.kill(p.target)}this.burst(p.x,p.y,p.color,p.type==='cannon'?12:5)}
update(dt){if(this.phase!=='wave'||this.paused)return;dt*=this.speed;this.spawnClock+=dt;while(this.spawnQueue.length&&this.spawnQueue[0].time<=this.spawnClock)this.spawn(this.spawnQueue.shift().type);for(const e of this.enemies)if(e.active&&e.update(dt))this.leak(e);for(const t of this.towers){t.update(dt);if(!t.canFire())continue;let target=null,best=-1;for(const e of this.enemies){if(!e.active)continue;const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<=t.stats.range&&e.segment>best){best=e.segment;target=e}}if(target)this.fire(t,target)}for(const p of this.projectiles)if(p.active&&p.update(dt)){this.hit(p);p.active=false}this.projectiles=this.projectiles.filter(p=>p.active);this.enemies=this.enemies.filter(e=>e.active);for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt}this.particles=this.particles.filter(q=>q.life>0);for(const f of this.floaters){f.life-=dt;f.y-=28*dt}this.floaters=this.floaters.filter(f=>f.life>0);if(!this.spawnQueue.length&&!this.enemies.length&&this.phase==='wave')this.clearWave();this.renderHud()}
clearWave(){const bonus=WAVES[this.waveIndex].bonus;this.gold+=bonus;this.waveIndex++;if(this.waveIndex>=WAVES.length){this.phase='won';this.toast('DUSTWALL SAVED!',5000);this.start.classList.add('hidden');return}this.phase='build';this.waveTotal=countWave(this.waveIndex);this.waveDefeated=0;this.toast(`WAVE CLEARED · +${bonus} GOLD`,2500);this.renderHud()}
burst(x,y,color,n){for(let i=0;i<n&&this.particles.length<220;i++){const a=Math.random()*Math.PI*2,s=20+Math.random()*70;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,color,size:2+Math.random()*3})}}
loop(t){try{const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;this.update(dt);this.draw()}catch(err){console.error(err);this.toast('GAME ERROR — RELOAD',5000)}requestAnimationFrame(n=>this.loop(n))}
draw(){const c=this.ctx;c.fillStyle='#c9894f';c.fillRect(0,0,720,1120);this.drawWorld(c);for(const e of this.enemies)if(e.active)this.drawEnemy(c,e);for(const p of this.projectiles)if(p.active){c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.type==='cannon'?6:3,0,Math.PI*2);c.fill()}for(const t of this.towers)this.drawTower(c,t);for(const pad of this.pads)if(!pad.tower)this.drawPad(c,pad);for(const q of this.particles){c.globalAlpha=Math.max(0,q.life*2);c.fillStyle=q.color;c.fillRect(q.x-q.size/2,q.y-q.size/2,q.size,q.size)}c.globalAlpha=1;for(const f of this.floaters){c.globalAlpha=Math.min(1,f.life*2);c.fillStyle=f.color;c.font='bold 20px Arial';c.textAlign='center';c.strokeStyle='#000';c.lineWidth=4;c.strokeText(f.text,f.x,f.y);c.fillText(f.text,f.x,f.y)}c.globalAlpha=1}
drawWorld(c){c.fillStyle='#d89a5d';for(let i=0;i<35;i++){const x=(i*149)%720,y=(i*263)%1120;c.fillRect(x,y,4,2)}c.strokeStyle='#6e685f';c.lineWidth=34;c.lineJoin='round';c.lineCap='round';c.beginPath();MAP.path.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.stroke();c.strokeStyle='#b6a58b';c.lineWidth=22;c.stroke();c.strokeStyle='#4f4a45';c.lineWidth=3;c.setLineDash([12,18]);c.stroke();c.setLineDash([]);c.save();c.translate(MAP.base.x,MAP.base.y);c.fillStyle='#0c467a';c.strokeStyle='#8dd6ff';c.lineWidth=7;c.beginPath();c.arc(0,0,74,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#e7f0f5';c.fillRect(-42,-36,84,72);c.fillStyle='#3d8fd0';c.fillRect(-30,-23,60,46);c.restore()}
drawPad(c,p){c.save();c.translate(p.x,p.y);c.fillStyle='#24445f';c.strokeStyle='#7fd0ff';c.lineWidth=4;c.beginPath();c.arc(0,0,28,0,Math.PI*2);c.fill();c.stroke();const price=TOWERS[p.type].cost;c.fillStyle='#1879bf';c.strokeStyle='#0b2e4d';c.lineWidth=3;c.fillRect(-35,-66,70,38);c.strokeRect(-35,-66,70,38);c.fillStyle='#ffd22d';c.beginPath();c.arc(-19,-47,9,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='bold 18px Arial';c.textAlign='center';c.strokeStyle='#000';c.lineWidth=4;c.strokeText(price,8,-41);c.fillText(price,8,-41);c.restore()}
drawTower(c,t){const s=t.stats;c.save();c.translate(t.x,t.y);c.fillStyle='#edf5f8';c.strokeStyle=s.accent;c.lineWidth=5;c.beginPath();c.arc(0,0,25+t.level*2,0,Math.PI*2);c.fill();c.stroke();c.rotate(t.angle);c.fillStyle=s.accent;c.fillRect(-7,-8,28+t.level*3,16);if(t.type==='cannon'){c.fillStyle='#526777';c.fillRect(7,-11,25,22)}if(t.type==='freeze'){c.fillStyle='#aef8ff';c.beginPath();c.arc(6,0,11,0,Math.PI*2);c.fill()}c.restore();c.fillStyle='#fff';c.font='bold 11px Arial';c.textAlign='center';c.fillText(`L${t.level}`,t.x,t.y+43)}
drawEnemy(c,e){c.save();c.translate(e.x,e.y);c.rotate(e.angle);c.fillStyle='#1d2b27';c.fillRect(-e.size*.7,e.size*.45,e.size*.45,e.size*.75);c.fillRect(e.size*.2,e.size*.45,e.size*.45,e.size*.75);c.fillStyle=e.color;c.beginPath();c.arc(0,0,e.size,0,Math.PI*2);c.fill();c.fillStyle='#173d25';c.beginPath();c.arc(1,-e.size*.35,e.size*.82,Math.PI,0);c.fill();c.restore();if(e.hp<e.maxHp){c.fillStyle='#18201c';c.fillRect(e.x-13,e.y-e.size-9,26,4);c.fillStyle='#58e65f';c.fillRect(e.x-13,e.y-e.size-9,26*Math.max(0,e.hp/e.maxHp),4)}}}
function boot(){try{new Game()}catch(err){console.error(err);document.body.innerHTML='<div style="color:white;padding:30px;font:20px system-ui">FUN TD failed to start. Please reload.</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
