(()=>{
const MAP={worldW:720,worldH:1120,base:{x:112,y:600,r:82},path:[[710,145],[520,145],[520,315],[650,315],[650,500],[430,500],[430,690],[620,690],[620,930],[330,930],[330,780],[210,780],[210,630],[150,630]],pads:[{x:430,y:235,type:'gun'},{x:610,y:220,type:'cannon'},{x:475,y:400,type:'gun'},{x:555,y:580,type:'freeze'},{x:335,y:585,type:'cannon'},{x:520,y:805,type:'gun'},{x:255,y:855,type:'freeze'},{x:490,y:1010,type:'cannon'},{x:210,y:1000,type:'gun'},{x:115,y:745,type:'gun'}]};
const TOWERS={gun:{name:'GUN TOWER',cost:100,damage:18,rate:4.5,range:155,projectileSpeed:720,color:'#67d3ff',accent:'#1e78cc'},cannon:{name:'CANNON',cost:200,damage:55,rate:.9,range:190,projectileSpeed:330,splash:55,color:'#ffb24b',accent:'#df6f22'},freeze:{name:'FREEZE',cost:150,damage:8,rate:1.8,range:160,projectileSpeed:560,slow:.30,color:'#9df8ff',accent:'#2ca7d9'}};
const ENEMIES={grunt:{hp:34,speed:54,reward:5,damage:1,size:10,color:'#36d058'},scout:{hp:27,speed:76,reward:7,damage:1,size:8,color:'#79ee55'},armored:{hp:105,speed:40,reward:12,damage:2,size:12,color:'#23934a'},heavy:{hp:280,speed:28,reward:20,damage:5,size:17,color:'#18743f'},boss:{hp:2300,speed:20,reward:250,damage:15,size:30,color:'#0e5938'}};
const g=(type,count,interval=.42,gap=0)=>({type,count,interval,gap});
const WAVES=[[g('grunt',8,.68)],[g('grunt',12,.62)],[g('grunt',16,.58)],[g('grunt',22,.54)],[g('grunt',28,.50)],[g('grunt',20,.46),g('scout',8,.52,1.2)],[g('grunt',26,.44),g('scout',10,.48,1.1)],[g('grunt',30,.42),g('armored',6,.66,1.1)],[g('grunt',36,.40),g('scout',14,.44,1)],[g('grunt',42,.38),g('armored',8,.60,1)],[g('grunt',48,.36),g('scout',16,.40,.9)],[g('grunt',55,.35),g('armored',10,.56,.9)],[g('grunt',60,.34),g('heavy',4,.9,1)],[g('grunt',66,.33),g('scout',20,.38,.8),g('armored',8,.52,.8)],[g('grunt',72,.32),g('heavy',5,.82,.8)],[g('grunt',82,.30),g('scout',22,.34,.8)],[g('grunt',90,.29),g('armored',14,.48,.7)],[g('grunt',100,.28),g('heavy',7,.75,.7)],[g('grunt',110,.27),g('scout',28,.32,.7),g('armored',16,.46,.7)],[g('boss',1,1),g('grunt',90,.29,1.5),g('heavy',8,.72,.8)]].map((groups,i)=>({groups,bonus:75+i*10}));
const countWave=i=>WAVES[i]?WAVES[i].groups.reduce((n,x)=>n+x.count,0):0;
const towerStats=(type,level)=>{const b=TOWERS[type],n=level-1;return{...b,damage:b.damage*(1+n*.55),rate:b.rate*(1+n*.16),range:b.range*(1+n*.07),splash:b.splash?b.splash+n*8:0,slow:b.slow?Math.min(.55,b.slow+n*.07):0}};
const upgradeCost=(type,level)=>level<4?Math.round([0,1,2,4][level]*TOWERS[type].cost):0;
const rr=(c,x,y,w,h,r)=>{r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.lineTo(x+w-r,y);c.quadraticCurveTo(x+w,y,x+w,y+r);c.lineTo(x+w,y+h-r);c.quadraticCurveTo(x+w,y+h,x+w-r,y+h);c.lineTo(x+r,y+h);c.quadraticCurveTo(x,y+h,x,y+h-r);c.lineTo(x,y+r);c.quadraticCurveTo(x,y,x+r,y);c.closePath()};
class Enemy{constructor(type){this.reset(type)}reset(type){const d=ENEMIES[type];Object.assign(this,d);this.type=type;this.maxHp=d.hp;this.hp=d.hp;this.segment=0;this.x=MAP.path[0][0];this.y=MAP.path[0][1];this.slow=0;this.slowTime=0;this.active=true;this.angle=0;this.lane=(Math.random()*2-1)*11;return this}update(dt){if(this.slowTime>0)this.slowTime-=dt;else this.slow=0;let travel=this.speed*(1-this.slow)*dt;while(travel>0&&this.segment<MAP.path.length-1){const b=MAP.path[this.segment+1],dx=b[0]-this.x,dy=b[1]-this.y,d=Math.hypot(dx,dy);this.angle=Math.atan2(dy,dx);if(travel>=d){this.x=b[0];this.y=b[1];this.segment++;travel-=d}else{this.x+=dx/d*travel;this.y+=dy/d*travel;travel=0}}return this.segment>=MAP.path.length-1}}
class Tower{constructor(type,x,y){this.type=type;this.x=x;this.y=y;this.level=1;this.cooldown=0;this.angle=-Math.PI/2;this.recoil=0;this.pulse=.65}get stats(){return towerStats(this.type,this.level)}update(dt){this.cooldown-=dt;this.recoil=Math.max(0,this.recoil-dt*7);this.pulse=Math.max(0,this.pulse-dt)}canFire(){return this.cooldown<=0}fired(){this.cooldown=1/this.stats.rate;this.recoil=1}}
class Projectile{constructor(x,y,target,stats,type){this.x=x;this.y=y;this.target=target;this.speed=stats.projectileSpeed;this.damage=stats.damage;this.splash=stats.splash||0;this.slow=stats.slow||0;this.type=type;this.color=stats.color;this.active=true;this.px=x;this.py=y}update(dt){if(!this.active||!this.target||!this.target.active){this.active=false;return false}this.px=this.x;this.py=this.y;const dx=this.target.x-this.x,dy=this.target.y-this.y,d=Math.hypot(dx,dy),step=this.speed*dt;if(d<=step+7){this.x=this.target.x;this.y=this.target.y;return true}this.x+=dx/d*step;this.y+=dy/d*step;return false}}
class Game{constructor(){this.canvas=document.getElementById('game');this.ctx=this.canvas.getContext('2d');this.canvas.width=720;this.canvas.height=1120;this.goldEl=document.getElementById('gold');this.waveEl=document.getElementById('wave');this.hpEl=document.getElementById('hp');this.fill=document.getElementById('progressFill');this.progress=document.getElementById('progressText');this.start=document.getElementById('startWave');this.menu=document.getElementById('towerMenu');this.toastEl=document.getElementById('toast');this.reset();this.bind();this.fit();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
reset(){this.phase='intro';this.gold=600;this.baseHp=100;this.waveIndex=0;this.waveTotal=countWave(0);this.waveDefeated=0;this.spawnQueue=[];this.spawnClock=0;this.enemies=[];this.towers=[];this.projectiles=[];this.particles=[];this.floaters=[];this.speed=1;this.paused=false;this.combo=0;this.comboTimer=0;this.comboPeak=0;this.waveLeaks=0;this.banner=null;this.pads=MAP.pads.map((p,i)=>({...p,id:i,tower:null}));this.renderHud()}
bind(){document.getElementById('play').onclick=()=>{document.getElementById('intro').classList.add('hidden');this.phase='build';this.toast('BUILD YOUR DEFENSE');this.renderHud()};this.start.onclick=()=>this.startWave();document.getElementById('pause').onclick=()=>{this.paused=!this.paused;this.toast(this.paused?'PAUSED':'RESUMED')};document.getElementById('speed').onclick=e=>{this.speed=this.speed===1?2:1;e.currentTarget.textContent=this.speed+'×'};document.getElementById('sound').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♪'?'×':'♪'};this.canvas.addEventListener('pointerdown',e=>{e.preventDefault();this.tap(e)});addEventListener('resize',()=>this.fit())}
fit(){const ratio=720/1120,w=innerWidth,h=innerHeight;this.canvas.style.width=(w/h<ratio?w:h*ratio)+'px';this.canvas.style.height=(w/h<ratio?w/ratio:h)+'px'}
renderHud(){this.goldEl.textContent=Math.floor(this.gold);this.waveEl.textContent=Math.min(20,this.waveIndex+1);this.hpEl.textContent=this.baseHp;this.progress.textContent=`${this.waveDefeated} / ${this.waveTotal}`;this.fill.style.width=(this.waveTotal?Math.min(100,this.waveDefeated/this.waveTotal*100):0)+'%';this.start.textContent=`START WAVE ${Math.min(20,this.waveIndex+1)}`;this.start.classList.toggle('hidden',this.phase!=='build')}
toast(msg,time=1800){clearTimeout(this.toastTimer);this.toastEl.textContent=msg;this.toastEl.classList.add('show');this.toastTimer=setTimeout(()=>this.toastEl.classList.remove('show'),time)}closeMenu(){this.menu.classList.add('hidden');this.menu.innerHTML=''}pointer(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*1120/r.height}}tap(e){if(this.phase==='intro'||this.paused)return;const p=this.pointer(e),pad=this.pads.find(q=>Math.hypot(q.x-p.x,q.y-p.y)<64);if(!pad){this.closeMenu();return}pad.tower?this.upgradeMenu(pad):this.buildMenu(pad)}
buildMenu(pad){this.menu.classList.remove('hidden');this.menu.innerHTML=Object.entries(TOWERS).map(([k,t])=>`<button data-build="${k}" ${this.gold<t.cost?'disabled':''}>${t.name}<small>● ${t.cost}</small></button>`).join('')+'<button class="close wide">CLOSE</button>';this.menu.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>this.build(pad,b.dataset.build));this.menu.querySelector('.close').onclick=()=>this.closeMenu()}
upgradeMenu(pad){const t=pad.tower,cost=upgradeCost(t.type,t.level),s=t.stats;this.menu.classList.remove('hidden');this.menu.innerHTML=`<button class="wide" disabled>${TOWERS[t.type].name} · LEVEL ${t.level}<small>DMG ${Math.round(s.damage)} · RNG ${Math.round(s.range)}</small></button>${t.level<4?`<button class="upgrade wide" data-up ${this.gold<cost?'disabled':''}>UPGRADE — ${cost}</button>`:'<button class="wide" disabled>MAX LEVEL</button>'}<button class="close wide">CLOSE</button>`;const up=this.menu.querySelector('[data-up]');if(up)up.onclick=()=>this.upgrade(pad);this.menu.querySelector('.close').onclick=()=>this.closeMenu()}
build(pad,type){const cost=TOWERS[type].cost;if(pad.tower||this.gold<cost)return;this.gold-=cost;pad.tower=new Tower(type,pad.x,pad.y);this.towers.push(pad.tower);this.burst(pad.x,pad.y,TOWERS[type].color,24);this.ring(pad.x,pad.y,TOWERS[type].color,.55,18,62);this.floaters.push({x:pad.x,y:pad.y-45,text:'ONLINE!',life:.8,color:'#dff8ff'});this.closeMenu();this.renderHud()}
upgrade(pad){const t=pad.tower,cost=upgradeCost(t.type,t.level);if(!cost||this.gold<cost)return;this.gold-=cost;t.level++;t.pulse=.8;this.burst(t.x,t.y,'#ffe16a',32);this.ring(t.x,t.y,'#ffe16a',.65,20,76);this.floaters.push({x:t.x,y:t.y-52,text:`LEVEL ${t.level}!`,life:1,color:'#ffe46a'});this.upgradeMenu(pad);this.renderHud()}
startWave(){if(this.phase!=='build')return;this.phase='wave';this.closeMenu();this.spawnQueue=[];let time=.8;for(const group of WAVES[this.waveIndex].groups){time+=group.gap||0;for(let i=0;i<group.count;i++){this.spawnQueue.push({time,type:group.type});time+=group.interval}time+=.55}this.spawnClock=0;this.waveTotal=countWave(this.waveIndex);this.waveDefeated=0;this.waveLeaks=0;this.combo=0;this.comboTimer=0;this.comboPeak=0;this.banner={text:`WAVE ${this.waveIndex+1} INCOMING`,life:1.1,color:'#fff'};this.renderHud()}
spawn(type){this.enemies.push(new Enemy(type))}
kill(e){if(!e.active)return;e.active=false;this.combo=this.comboTimer>0?this.combo+1:1;this.comboTimer=1.35;this.comboPeak=Math.max(this.comboPeak,this.combo);let bonus=0;if(this.combo>=10)bonus=Math.min(5,Math.floor(this.combo/10));const reward=e.reward+bonus;this.gold+=reward;this.waveDefeated++;this.floaters.push({x:e.x,y:e.y,text:`+${reward}`,life:1,color:bonus?'#fff06a':'#ffd43b'});if(this.combo===10||this.combo===25||this.combo===50||this.combo===100){this.banner={text:`${this.combo}× COMBO!`,life:.8,color:'#ffe55c'};this.ring(e.x,e.y,'#ffe55c',.45,10,58)}this.burst(e.x,e.y,e.color,9)}
leak(e){e.active=false;this.waveLeaks++;this.combo=0;this.comboTimer=0;this.baseHp=Math.max(0,this.baseHp-e.damage);this.burst(MAP.base.x+42,MAP.base.y,'#ff6655',14);this.ring(MAP.base.x,MAP.base.y,'#ff6655',.45,60,95);if(this.baseHp<=0){this.phase='lost';this.start.classList.add('hidden');this.toast('BASE LOST',4000)}}
fire(t,target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);t.fired();this.projectiles.push(new Projectile(t.x+Math.cos(t.angle)*25,t.y+Math.sin(t.angle)*25,target,t.stats,t.type));this.burst(t.x+Math.cos(t.angle)*27,t.y+Math.sin(t.angle)*27,t.stats.color,t.type==='cannon'?7:4)}
hit(p){if(p.splash){for(const e of this.enemies)if(e.active&&Math.hypot(e.x-p.x,e.y-p.y)<=p.splash){e.hp-=p.damage;if(e.hp<=0)this.kill(e)}}else if(p.target&&p.target.active){p.target.hp-=p.damage;if(p.slow){p.target.slow=Math.max(p.target.slow,p.slow);p.target.slowTime=2.2}if(p.target.hp<=0)this.kill(p.target)}this.burst(p.x,p.y,p.color,p.type==='cannon'?20:8);if(p.type==='cannon')this.ring(p.x,p.y,'#ffb24b',.28,16,50);if(p.type==='freeze')this.ring(p.x,p.y,'#bffcff',.22,8,30)}
update(dt){if(this.paused)return;if(this.comboTimer>0){this.comboTimer-=dt*this.speed;if(this.comboTimer<=0)this.combo=0}if(this.banner){this.banner.life-=dt;if(this.banner.life<=0)this.banner=null}for(const t of this.towers)t.update(dt);if(this.phase!=='wave')return;dt*=this.speed;this.spawnClock+=dt;while(this.spawnQueue.length&&this.spawnQueue[0].time<=this.spawnClock)this.spawn(this.spawnQueue.shift().type);for(const e of this.enemies)if(e.active&&e.update(dt))this.leak(e);for(const t of this.towers){if(!t.canFire())continue;let target=null,best=-1;for(const e of this.enemies){if(!e.active)continue;const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<=t.stats.range&&e.segment>best){best=e.segment;target=e}}if(target)this.fire(t,target)}for(const p of this.projectiles)if(p.active&&p.update(dt)){this.hit(p);p.active=false}this.projectiles=this.projectiles.filter(p=>p.active);this.enemies=this.enemies.filter(e=>e.active);for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.96;q.vy*=.96}this.particles=this.particles.filter(q=>q.life>0);for(const f of this.floaters){f.life-=dt;f.y-=f.ring?0:28*dt}this.floaters=this.floaters.filter(f=>f.life>0);if(!this.spawnQueue.length&&!this.enemies.length&&this.phase==='wave')this.clearWave();this.renderHud()}
clearWave(){const baseBonus=WAVES[this.waveIndex].bonus,flawless=this.waveLeaks===0,flawlessBonus=flawless?50+this.waveIndex*5:0,comboBonus=Math.min(100,Math.floor(this.comboPeak/10)*5),total=baseBonus+flawlessBonus+comboBonus;this.gold+=total;this.banner={text:flawless?`FLAWLESS! +${total} GOLD`:`WAVE CLEAR +${total} GOLD`,life:1.8,color:flawless?'#8cff88':'#ffe16a'};this.waveIndex++;if(this.waveIndex>=WAVES.length){this.phase='won';this.toast('DUSTWALL SAVED!',5000);this.start.classList.add('hidden');return}this.phase='build';this.waveTotal=countWave(this.waveIndex);this.waveDefeated=0;this.combo=0;this.comboTimer=0;this.renderHud()}
burst(x,y,color,n){for(let i=0;i<n&&this.particles.length<300;i++){const a=Math.random()*Math.PI*2,s=25+Math.random()*95;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.22+Math.random()*.36,color,size:2+Math.random()*3})}}
ring(x,y,color,life=.3,r0=12,r1=45){this.floaters.push({x,y,text:'',life,maxLife:life,color,ring:true,r0,r1})}
loop(t){try{const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;this.update(dt);this.draw()}catch(err){console.error(err);this.toast('GAME ERROR — RELOAD',5000)}requestAnimationFrame(n=>this.loop(n))}
draw(){const c=this.ctx;c.fillStyle='#c98a50';c.fillRect(0,0,720,1120);this.drawWorld(c);for(const e of this.enemies)if(e.active)this.drawEnemy(c,e);for(const p of this.projectiles)if(p.active)this.drawProjectile(c,p);for(const t of this.towers)this.drawTower(c,t);for(const pad of this.pads)if(!pad.tower)this.drawPad(c,pad);for(const q of this.particles){c.globalAlpha=Math.max(0,q.life*2.5);c.fillStyle=q.color;c.fillRect(q.x-q.size/2,q.y-q.size/2,q.size,q.size)}c.globalAlpha=1;for(const f of this.floaters){if(f.ring){const m=f.maxLife||.25,p=1-Math.max(0,f.life)/m,r=(f.r0||18)+p*((f.r1||42)-(f.r0||18));c.globalAlpha=Math.max(0,f.life/m);c.strokeStyle=f.color;c.lineWidth=4;c.beginPath();c.arc(f.x,f.y,r,0,Math.PI*2);c.stroke();continue}c.globalAlpha=Math.min(1,f.life*2);c.fillStyle=f.color;c.font='bold 21px Arial';c.textAlign='center';c.strokeStyle='#111';c.lineWidth=4;c.strokeText(f.text,f.x,f.y);c.fillText(f.text,f.x,f.y)}c.globalAlpha=1;this.drawCombo(c);if(this.banner)this.drawBanner(c)}
drawCombo(c){if(this.combo<3||this.phase!=='wave')return;c.save();c.globalAlpha=.95;c.textAlign='center';c.font=`900 ${Math.min(36,21+this.combo*.22)}px Arial`;c.fillStyle=this.combo>=25?'#ffe45e':'#fff';c.strokeStyle='#142033';c.lineWidth=6;c.strokeText(`${this.combo}× COMBO`,360,150);c.fillText(`${this.combo}× COMBO`,360,150);c.fillStyle='#182638';c.fillRect(300,162,120,7);c.fillStyle='#ffe45e';c.fillRect(300,162,120*Math.max(0,this.comboTimer/1.35),7);c.restore()}
drawBanner(c){const a=Math.min(1,this.banner.life*2);c.save();c.globalAlpha=a;c.textAlign='center';c.font='900 34px Arial';c.fillStyle=this.banner.color;c.strokeStyle='#101827';c.lineWidth=8;c.strokeText(this.banner.text,360,555);c.fillText(this.banner.text,360,555);c.restore()}
drawWorld(c){const grad=c.createLinearGradient(0,0,720,1120);grad.addColorStop(0,'#d69a5e');grad.addColorStop(1,'#bd7642');c.fillStyle=grad;c.fillRect(0,0,720,1120);c.globalAlpha=.14;c.fillStyle='#f4c47d';for(let i=0;i<48;i++){const x=(i*137+43)%720,y=(i*251+79)%1120;c.beginPath();c.arc(x,y,2+(i%3),0,Math.PI*2);c.fill()}c.globalAlpha=1;this.drawDecor(c);c.save();c.lineJoin='round';c.lineCap='round';c.strokeStyle='#5b5045';c.lineWidth=58;c.shadowColor='#0005';c.shadowBlur=10;c.shadowOffsetY=8;c.beginPath();MAP.path.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.stroke();c.shadowColor='transparent';c.strokeStyle='#8e7f6c';c.lineWidth=48;c.stroke();c.strokeStyle='#c9b896';c.lineWidth=36;c.stroke();c.strokeStyle='#6c6258';c.lineWidth=3;c.setLineDash([14,15]);c.stroke();c.setLineDash([]);c.restore();this.drawBase(c)}
drawDecor(c){const rocks=[[65,170,13],[280,160,9],[165,330,11],[350,325,7],[65,930,12],[660,1030,11],[405,1060,8],[675,580,10],[285,470,7]];for(const [x,y,r] of rocks){c.fillStyle='#8a5b3b';c.beginPath();c.ellipse(x,y,r,r*.65,-.3,0,Math.PI*2);c.fill();c.fillStyle='#b77b50';c.beginPath();c.ellipse(x-3,y-2,r*.55,r*.3,-.3,0,Math.PI*2);c.fill()}const cracks=[[160,220],[300,700],[610,600],[430,870],[125,1050]];c.strokeStyle='#9b6039';c.lineWidth=2;for(const [x,y] of cracks){c.beginPath();c.moveTo(x,y);c.lineTo(x+10,y+8);c.lineTo(x+2,y+18);c.moveTo(x+10,y+8);c.lineTo(x+22,y+3);c.stroke()}for(const [x,y] of [[45,1030],[685,990]])this.drawPalm(c,x,y);this.drawCrates(c,55,390);this.drawCrates(c,630,415);this.drawSandbags(c,265,610);this.drawSandbags(c,540,955)}
drawPalm(c,x,y){c.save();c.translate(x,y);c.strokeStyle='#654223';c.lineWidth=10;c.beginPath();c.moveTo(0,40);c.quadraticCurveTo(-5,10,5,-32);c.stroke();c.strokeStyle='#617e31';c.lineWidth=8;for(let i=0;i<6;i++){const a=i*Math.PI/3;c.beginPath();c.moveTo(5,-32);c.lineTo(5+Math.cos(a)*36,-32+Math.sin(a)*23);c.stroke()}c.restore()}drawCrates(c,x,y){c.fillStyle='#7a5234';c.strokeStyle='#4d3425';c.lineWidth=3;for(let i=0;i<2;i++){c.fillRect(x+i*22,y+i*8,20,20);c.strokeRect(x+i*22,y+i*8,20,20);c.beginPath();c.moveTo(x+i*22,y+i*8);c.lineTo(x+i*22+20,y+i*8+20);c.stroke()}}drawSandbags(c,x,y){c.fillStyle='#b89967';c.strokeStyle='#735f45';c.lineWidth=2;for(let i=0;i<4;i++){c.beginPath();c.ellipse(x+i*18,y+(i%2)*5,11,6,0,0,Math.PI*2);c.fill();c.stroke()}}
drawBase(c){const x=MAP.base.x,y=MAP.base.y;c.save();c.translate(x,y);c.shadowColor='#0007';c.shadowBlur=16;c.shadowOffsetY=10;c.fillStyle='#0b2c50';c.strokeStyle='#8ddcff';c.lineWidth=7;c.beginPath();c.arc(0,0,86,0,Math.PI*2);c.fill();c.stroke();c.shadowColor='transparent';c.fillStyle='#e9f3f8';c.strokeStyle='#2e83c5';c.lineWidth=6;rr(c,-58,-48,116,96,18);c.fill();c.stroke();c.fillStyle='#1e5f9a';rr(c,-42,-32,84,64,12);c.fill();c.fillStyle='#52b8ff';rr(c,-27,-19,54,38,8);c.fill();c.fillStyle='#d9f6ff';rr(c,-18,-12,36,24,6);c.fill();c.fillStyle='#18324b';c.fillRect(-10,-8,20,16);c.fillStyle='#225d92';c.fillRect(-68,-13,16,26);c.fillRect(52,-13,16,26);c.fillStyle='#f7d44c';c.beginPath();c.arc(-58,-54,6,0,Math.PI*2);c.arc(58,-54,6,0,Math.PI*2);c.fill();c.restore()}
drawPad(c,p){const price=TOWERS[p.type].cost,afford=this.gold>=price;c.save();c.translate(p.x,p.y);c.shadowColor='#0006';c.shadowBlur=8;c.shadowOffsetY=5;c.fillStyle='#153853';c.strokeStyle=afford?'#7fdcff':'#4f6572';c.lineWidth=5;c.beginPath();c.arc(0,0,31,0,Math.PI*2);c.fill();c.stroke();c.shadowColor='transparent';c.strokeStyle=afford?'#9bf0ff':'#5b6c75';c.lineWidth=2;c.beginPath();c.arc(0,0,21,0,Math.PI*2);c.stroke();c.fillStyle='#0a2638';c.beginPath();c.arc(0,0,10,0,Math.PI*2);c.fill();c.fillStyle=afford?'#1c8ed1':'#4a5660';c.strokeStyle='#0a2f4a';c.lineWidth=3;rr(c,-38,-73,76,38,8);c.fill();c.stroke();c.fillStyle=afford?'#ffd72f':'#c0aa55';c.beginPath();c.arc(-21,-54,10,0,Math.PI*2);c.fill();c.strokeStyle='#e79d00';c.lineWidth=2;c.stroke();c.fillStyle='#fff';c.font='bold 19px Arial';c.textAlign='center';c.strokeStyle='#0a0a0a';c.lineWidth=4;c.strokeText(price,10,-47);c.fillText(price,10,-47);c.restore()}
drawTower(c,t){const s=t.stats,r=27+t.level*2;c.save();c.translate(t.x,t.y);if(t.pulse>0){c.globalAlpha=Math.min(1,t.pulse*1.5);c.strokeStyle='#fff6a8';c.lineWidth=5;c.beginPath();c.arc(0,0,r+16+(1-t.pulse)*18,0,Math.PI*2);c.stroke();c.globalAlpha=1}c.shadowColor='#0007';c.shadowBlur=10;c.shadowOffsetY=6;c.fillStyle='#173d59';c.strokeStyle='#7fdcff';c.lineWidth=4;c.beginPath();c.arc(0,0,r+7,0,Math.PI*2);c.fill();c.stroke();c.shadowColor='transparent';c.fillStyle='#eaf4f8';c.strokeStyle=s.accent;c.lineWidth=5;c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.fill();c.stroke();if(t.level>=2){c.strokeStyle='#ffe16a';c.lineWidth=3;c.beginPath();c.arc(0,0,r-6,0,Math.PI*2);c.stroke()}c.fillStyle='#b6d9ec';c.beginPath();c.arc(0,0,15+t.level,0,Math.PI*2);c.fill();c.rotate(t.angle);c.translate(-t.recoil*4,0);if(t.type==='gun'){c.fillStyle=s.accent;c.fillRect(-5,-7,30+t.level*4,14);c.fillStyle='#d6f3ff';c.fillRect(10,-4,15+t.level*2,8);if(t.level>=2){c.fillStyle='#16598f';c.fillRect(0,-11,20+t.level*2,4)}if(t.level>=3)c.fillRect(0,7,20+t.level*2,4);if(t.level===4){c.fillStyle='#ffe16a';c.fillRect(15,-2,16,4)}}else if(t.type==='cannon'){c.fillStyle='#526777';c.fillRect(-2,-12,34+t.level*4,24);c.fillStyle=s.accent;c.fillRect(10,-8,24+t.level*3,16);if(t.level>=3){c.fillStyle='#ffe16a';c.fillRect(5,-15,16,4);c.fillRect(5,11,16,4)}}else{c.fillStyle='#8cefff';c.beginPath();c.arc(8,0,14+t.level,0,Math.PI*2);c.fill();c.strokeStyle='#d9ffff';c.lineWidth=3;c.stroke();c.fillStyle=s.accent;c.fillRect(6,-5,22+t.level*2,10);if(t.level>=3){c.strokeStyle='#8cf5ff';c.lineWidth=3;c.beginPath();c.arc(2,0,23+t.level*2,0,Math.PI*2);c.stroke()}}c.restore();c.fillStyle='#fff';c.font='bold 11px Arial';c.textAlign='center';c.strokeStyle='#111';c.lineWidth=3;c.strokeText(`L${t.level}`,t.x,t.y+48);c.fillText(`L${t.level}`,t.x,t.y+48)}
drawEnemy(c,e){const ox=Math.cos(e.angle+Math.PI/2)*e.lane,oy=Math.sin(e.angle+Math.PI/2)*e.lane,x=e.x+ox,y=e.y+oy;c.save();c.translate(x,y);c.rotate(e.angle);if(e.slow>0){c.fillStyle='#9df8ff55';c.beginPath();c.arc(0,0,e.size+5,0,Math.PI*2);c.fill()}c.fillStyle='#1c2b25';c.fillRect(-e.size*.7,e.size*.4,e.size*.45,e.size*.8);c.fillRect(e.size*.2,e.size*.4,e.size*.45,e.size*.8);c.fillStyle=e.color;c.strokeStyle='#174328';c.lineWidth=2;c.beginPath();c.arc(0,0,e.size,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#173d25';c.beginPath();c.arc(0,-e.size*.35,e.size*.82,Math.PI,0);c.fill();c.fillStyle='#dff7d8';c.fillRect(e.size*.2,-2,3,3);c.restore();if(e.hp<e.maxHp){c.fillStyle='#17201c';c.fillRect(x-14,y-e.size-10,28,4);c.fillStyle='#58e65f';c.fillRect(x-14,y-e.size-10,28*Math.max(0,e.hp/e.maxHp),4)}}
drawProjectile(c,p){if(p.type==='gun'){c.strokeStyle='#bdefff';c.lineWidth=3;c.beginPath();c.moveTo(p.px,p.py);c.lineTo(p.x,p.y);c.stroke();c.fillStyle='#fff';c.beginPath();c.arc(p.x,p.y,2.5,0,Math.PI*2);c.fill()}else if(p.type==='cannon'){c.fillStyle='#ffb24b';c.strokeStyle='#7c3b13';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,7,0,Math.PI*2);c.fill();c.stroke()}else{c.fillStyle='#bffcff';c.strokeStyle='#4cc7e9';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,5,0,Math.PI*2);c.fill();c.stroke()}}
}
function boot(){try{new Game()}catch(err){console.error(err);document.body.innerHTML='<div style="color:white;padding:30px;font:20px system-ui">FUN TD failed to start. Please reload.</div>'}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();