(()=>{
const MAP={worldW:720,worldH:1120,base:{x:590,y:170,r:80},path:[[35,1010],[180,1010],[180,850],[520,850],[520,690],[300,690],[300,515],[610,515],[610,350],[430,350],[430,170],[535,170]],pads:[{x:85,y:900,type:'gun'},{x:285,y:930,type:'cannon'},{x:455,y:770,type:'freeze'},{x:160,y:730,type:'gun'},{x:395,y:605,type:'cannon'},{x:640,y:610,type:'freeze'},{x:520,y:435,type:'gun'},{x:310,y:405,type:'cannon'},{x:520,y:260,type:'gun'},{x:670,y:210,type:'freeze'}]};
const TOWERS={gun:{name:'GUN TOWER',cost:100,damage:18,rate:4.5,range:155,projectileSpeed:720,color:'#67d3ff',accent:'#1e78cc'},cannon:{name:'CANNON',cost:200,damage:55,rate:.9,range:190,projectileSpeed:330,splash:55,color:'#ffb24b',accent:'#df6f22'},freeze:{name:'FREEZE',cost:150,damage:8,rate:1.8,range:160,projectileSpeed:560,slow:.3,color:'#9df8ff',accent:'#2ca7d9'}};
const ENEMIES={grunt:{hp:38,speed:52,reward:5,damage:1,size:10,color:'#55d15b'},scout:{hp:31,speed:74,reward:7,damage:1,size:8,color:'#95ef58'},armored:{hp:120,speed:38,reward:12,damage:2,size:12,color:'#429d51'},heavy:{hp:315,speed:27,reward:20,damage:5,size:17,color:'#287641'},splitter:{hp:78,speed:46,reward:10,damage:2,size:13,color:'#ff8a3c',split:true},mite:{hp:18,speed:70,reward:2,damage:1,size:6,color:'#ffbd58'},boss:{hp:2850,speed:17,reward:325,damage:18,size:33,color:'#d94f2f'}};
const g=(type,count,interval=.42,gap=0)=>({type,count,interval,gap});
const WAVES=[[g('grunt',10,.66)],[g('grunt',15,.6)],[g('grunt',18,.56),g('scout',4,.6,.8)],[g('grunt',24,.52)],[g('grunt',28,.5),g('splitter',3,.8,1)],[g('grunt',24,.46),g('scout',10,.5,1)],[g('grunt',30,.44),g('splitter',5,.72,.9)],[g('grunt',32,.42),g('armored',7,.64,1)],[g('grunt',38,.4),g('scout',16,.43,.9)],[g('grunt',40,.39),g('splitter',8,.66,.9),g('armored',6,.62,.8)],[g('grunt',48,.36),g('scout',18,.4,.8)],[g('grunt',54,.35),g('armored',11,.54,.8),g('splitter',8,.62,.7)],[g('grunt',58,.34),g('heavy',4,.9,.8)],[g('grunt',64,.33),g('scout',20,.38,.7),g('splitter',12,.58,.7)],[g('grunt',70,.32),g('heavy',6,.8,.7)],[g('grunt',78,.3),g('scout',22,.34,.7),g('splitter',14,.54,.6)],[g('grunt',86,.29),g('armored',14,.48,.6)],[g('grunt',94,.28),g('heavy',7,.74,.6),g('splitter',14,.52,.6)],[g('grunt',100,.27),g('scout',26,.32,.6),g('armored',16,.46,.6),g('splitter',18,.5,.5)],[g('boss',1,1),g('grunt',78,.29,1.4),g('splitter',18,.5,.7),g('heavy',8,.72,.7)]].map((groups,i)=>({groups,bonus:95+i*10}));
const countWave=i=>WAVES[i]?WAVES[i].groups.reduce((n,x)=>n+x.count,0):0;
const stats=(type,l)=>{const b=TOWERS[type],n=l-1;return{...b,damage:b.damage*(1+n*.55),rate:b.rate*(1+n*.16),range:b.range*(1+n*.07),splash:b.splash?b.splash+n*8:0,slow:b.slow?Math.min(.55,b.slow+n*.07):0}};
const upgradeCost=(type,l)=>l<4?Math.round([0,1,2,4][l]*TOWERS[type].cost):0;
class Enemy{constructor(type,seed=null){Object.assign(this,ENEMIES[type]);this.type=type;this.maxHp=this.hp;this.segment=seed?.segment||0;this.x=seed?.x??MAP.path[0][0];this.y=seed?.y??MAP.path[0][1];this.slow=0;this.slowTime=0;this.active=true;this.angle=seed?.angle||0;this.lane=(Math.random()*2-1)*10}update(dt){if(this.slowTime>0)this.slowTime-=dt;else this.slow=0;let tr=this.speed*(1-this.slow)*dt;while(tr>0&&this.segment<MAP.path.length-1){const b=MAP.path[this.segment+1],dx=b[0]-this.x,dy=b[1]-this.y,d=Math.hypot(dx,dy);this.angle=Math.atan2(dy,dx);if(tr>=d){this.x=b[0];this.y=b[1];this.segment++;tr-=d}else{this.x+=dx/d*tr;this.y+=dy/d*tr;tr=0}}return this.segment>=MAP.path.length-1}}
class Tower{constructor(type,x,y,cost){this.type=type;this.x=x;this.y=y;this.level=1;this.cooldown=0;this.angle=-Math.PI/2;this.recoil=0;this.pulse=.6;this.invested=cost}get stats(){return stats(this.type,this.level)}update(dt){this.cooldown-=dt;this.recoil=Math.max(0,this.recoil-dt*7);this.pulse=Math.max(0,this.pulse-dt)}canFire(){return this.cooldown<=0}fired(){this.cooldown=1/this.stats.rate;this.recoil=1}}
class Projectile{constructor(x,y,target,s,type){Object.assign(this,{x,y,target,speed:s.projectileSpeed,damage:s.damage,splash:s.splash||0,slow:s.slow||0,type,color:s.color,active:true,px:x,py:y})}update(dt){if(!this.target?.active){this.active=false;return false}this.px=this.x;this.py=this.y;const dx=this.target.x-this.x,dy=this.target.y-this.y,d=Math.hypot(dx,dy),step=this.speed*dt;if(d<=step+7){this.x=this.target.x;this.y=this.target.y;return true}this.x+=dx/d*step;this.y+=dy/d*step;return false}}
class Game{constructor(){this.canvas=document.getElementById('game');this.ctx=this.canvas.getContext('2d');this.canvas.width=720;this.canvas.height=1120;this.goldEl=document.getElementById('gold');this.waveEl=document.getElementById('wave');this.hpEl=document.getElementById('hp');this.fill=document.getElementById('progressFill');this.progress=document.getElementById('progressText');this.start=document.getElementById('startWave');this.menu=document.getElementById('towerMenu');this.toastEl=document.getElementById('toast');this.reset();this.bind();this.fit();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
reset(){this.phase='intro';this.gold=700;this.baseHp=100;this.waveIndex=0;this.waveTotal=countWave(0);this.waveDefeated=0;this.spawnQueue=[];this.spawnClock=0;this.enemies=[];this.towers=[];this.projectiles=[];this.particles=[];this.floaters=[];this.speed=1;this.paused=false;this.combo=0;this.comboTimer=0;this.comboPeak=0;this.waveLeaks=0;this.banner=null;this.selectedPad=null;this.time=0;this.pads=MAP.pads.map((p,i)=>({...p,id:i,tower:null}));this.renderHud()}
bind(){document.getElementById('play').onclick=()=>{document.getElementById('intro').classList.add('hidden');this.phase='build';this.toast('ASHFALL FOUNDRY ONLINE');this.renderHud()};this.start.onclick=()=>this.startWave();document.getElementById('pause').onclick=()=>{this.paused=!this.paused;this.toast(this.paused?'PAUSED':'RESUMED')};document.getElementById('speed').onclick=e=>{this.speed=this.speed===1?2:1;e.currentTarget.textContent=this.speed+'×'};document.getElementById('sound').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♪'?'×':'♪'};this.canvas.addEventListener('pointerdown',e=>{e.preventDefault();this.tap(e)});addEventListener('resize',()=>this.fit())}
fit(){const ratio=720/1120,w=innerWidth,h=innerHeight;this.canvas.style.width=(w/h<ratio?w:h*ratio)+'px';this.canvas.style.height=(w/h<ratio?w/ratio:h)+'px'}
renderHud(){this.goldEl.textContent=Math.floor(this.gold);this.waveEl.textContent=Math.min(20,this.waveIndex+1);this.hpEl.textContent=this.baseHp;this.progress.textContent=`${this.waveDefeated} / ${this.waveTotal}`;this.fill.style.width=(this.waveTotal?Math.min(100,this.waveDefeated/this.waveTotal*100):0)+'%';this.start.textContent=`START WAVE ${Math.min(20,this.waveIndex+1)}`;this.start.classList.toggle('hidden',this.phase!=='build')}
toast(msg,time=1800){clearTimeout(this.toastTimer);this.toastEl.textContent=msg;this.toastEl.classList.add('show');this.toastTimer=setTimeout(()=>this.toastEl.classList.remove('show'),time)}closeMenu(){this.menu.classList.add('hidden');this.menu.innerHTML='';this.selectedPad=null}pointer(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*1120/r.height}}tap(e){if(this.phase==='intro'||this.paused)return;const p=this.pointer(e),pad=this.pads.find(q=>Math.hypot(q.x-p.x,q.y-p.y)<64);if(!pad){this.closeMenu();return}this.selectedPad=pad;pad.tower?this.upgradeMenu(pad):this.buildMenu(pad)}
buildMenu(pad){this.menu.classList.remove('hidden');this.menu.innerHTML=Object.entries(TOWERS).map(([k,t])=>`<button data-build="${k}" ${this.gold<t.cost?'disabled':''}>${t.name}<small>● ${t.cost}</small></button>`).join('')+'<button class="close wide">CLOSE</button>';this.menu.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>this.build(pad,b.dataset.build));this.menu.querySelector('.close').onclick=()=>this.closeMenu()}
upgradeMenu(pad){const t=pad.tower,c=upgradeCost(t.type,t.level),refund=Math.floor(t.invested*.7);this.menu.classList.remove('hidden');this.menu.innerHTML=`<button class="wide" disabled>${TOWERS[t.type].name} · LEVEL ${t.level}<small>DMG ${Math.round(t.stats.damage)} · RNG ${Math.round(t.stats.range)}</small></button>${t.level<4?`<button class="upgrade wide" data-up ${this.gold<c?'disabled':''}>UPGRADE — ${c}</button>`:'<button class="wide" disabled>MAX LEVEL</button>'}<button class="sell wide" data-sell>SELL — +${refund}</button><button class="close wide">CLOSE</button>`;this.menu.querySelector('[data-up]')?.addEventListener('click',()=>this.upgrade(pad));this.menu.querySelector('[data-sell]').onclick=()=>this.sell(pad);this.menu.querySelector('.close').onclick=()=>this.closeMenu()}
build(pad,type){const c=TOWERS[type].cost;if(pad.tower||this.gold<c)return;this.gold-=c;pad.tower=new Tower(type,pad.x,pad.y,c);this.towers.push(pad.tower);this.burst(pad.x,pad.y,TOWERS[type].color,22);this.closeMenu();this.renderHud()}upgrade(pad){const t=pad.tower,c=upgradeCost(t.type,t.level);if(!c||this.gold<c)return;this.gold-=c;t.invested+=c;t.level++;t.pulse=.8;this.burst(t.x,t.y,'#ffe16a',28);this.upgradeMenu(pad);this.renderHud()}sell(pad){const t=pad.tower;if(!t)return;const r=Math.floor(t.invested*.7);this.gold+=r;this.towers=this.towers.filter(x=>x!==t);pad.tower=null;this.floaters.push({x:pad.x,y:pad.y-30,text:`+${r}`,life:1,color:'#8cffc0'});this.closeMenu();this.renderHud()}
startWave(){if(this.phase!=='build')return;this.phase='wave';this.closeMenu();this.spawnQueue=[];let time=.7;for(const group of WAVES[this.waveIndex].groups){time+=group.gap||0;for(let i=0;i<group.count;i++){this.spawnQueue.push({time,type:group.type});time+=group.interval}time+=.5}this.spawnClock=0;this.waveTotal=countWave(this.waveIndex);this.waveDefeated=0;this.waveLeaks=0;this.combo=0;this.comboTimer=0;this.comboPeak=0;this.banner={text:`ASHFALL WAVE ${this.waveIndex+1}`,life:1.1,color:'#ffd2a3'};this.renderHud()}spawn(type,seed=null){this.enemies.push(new Enemy(type,seed))}
kill(e){if(!e.active)return;e.active=false;if(e.split){for(let i=0;i<2;i++)this.spawn('mite',{x:e.x+(i?6:-6),y:e.y,segment:e.segment,angle:e.angle});this.banner={text:'SPLITTER BURST!',life:.55,color:'#ffb15a'}}this.combo=this.comboTimer>0?this.combo+1:1;this.comboTimer=1.35;this.comboPeak=Math.max(this.comboPeak,this.combo);const bonus=this.combo>=10?Math.min(5,Math.floor(this.combo/10)):0,reward=e.reward+bonus;this.gold+=reward;this.waveDefeated++;this.floaters.push({x:e.x,y:e.y,text:`+${reward}`,life:1,color:'#ffe36b'});this.burst(e.x,e.y,e.color,e.split?14:8)}
leak(e){e.active=false;this.waveLeaks++;this.combo=0;this.baseHp=Math.max(0,this.baseHp-e.damage);this.burst(MAP.base.x,MAP.base.y,'#ff6655',12);if(this.baseHp<=0){this.phase='lost';this.toast('BASE LOST',4000)}}fire(t,target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);t.fired();this.projectiles.push(new Projectile(t.x+Math.cos(t.angle)*25,t.y+Math.sin(t.angle)*25,target,t.stats,t.type))}
hit(p){if(p.splash){for(const e of this.enemies)if(e.active&&Math.hypot(e.x-p.x,e.y-p.y)<=p.splash){e.hp-=p.damage;if(e.hp<=0)this.kill(e)}}else if(p.target?.active){p.target.hp-=p.damage;if(p.slow){p.target.slow=Math.max(p.target.slow,p.slow);p.target.slowTime=2.2}if(p.target.hp<=0)this.kill(p.target)}this.burst(p.x,p.y,p.color,p.type==='cannon'?14:6)}
update(dt){if(this.paused)return;this.time+=dt;if(this.comboTimer>0){this.comboTimer-=dt*this.speed;if(this.comboTimer<=0)this.combo=0}if(this.banner){this.banner.life-=dt;if(this.banner.life<=0)this.banner=null}for(const t of this.towers)t.update(dt);if(this.phase!=='wave')return;dt*=this.speed;this.spawnClock+=dt;while(this.spawnQueue.length&&this.spawnQueue[0].time<=this.spawnClock)this.spawn(this.spawnQueue.shift().type);for(const e of this.enemies)if(e.active&&e.update(dt))this.leak(e);for(const t of this.towers){if(!t.canFire())continue;let target=null,best=-1;for(const e of this.enemies){if(!e.active)continue;const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<=t.stats.range&&e.segment>best){best=e.segment;target=e}}if(target)this.fire(t,target)}for(const p of this.projectiles)if(p.active&&p.update(dt)){this.hit(p);p.active=false}this.projectiles=this.projectiles.filter(p=>p.active);this.enemies=this.enemies.filter(e=>e.active);for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt}this.particles=this.particles.filter(q=>q.life>0);for(const f of this.floaters){f.life-=dt;f.y-=26*dt}this.floaters=this.floaters.filter(f=>f.life>0);if(!this.spawnQueue.length&&!this.enemies.length&&this.phase==='wave')this.clearWave();this.renderHud()}
clearWave(){const flawless=this.waveLeaks===0,total=WAVES[this.waveIndex].bonus+(flawless?65+this.waveIndex*5:0)+Math.min(100,Math.floor(this.comboPeak/10)*5);this.gold+=total;this.banner={text:flawless?`FLAWLESS! +${total}`:`WAVE CLEAR +${total}`,life:1.5,color:flawless?'#9bffbf':'#ffe16a'};this.waveIndex++;if(this.waveIndex>=WAVES.length){this.phase='won';localStorage.setItem('funTD_sector3Clear','1');this.toast('SECTOR SAVED',5000);return}this.phase='build';this.waveTotal=countWave(this.waveIndex);this.waveDefeated=0;this.combo=0;this.renderHud()}
burst(x,y,color,n){for(let i=0;i<n&&this.particles.length<260;i++){const a=Math.random()*Math.PI*2,s=25+Math.random()*80;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.2+Math.random()*.35,color,size:2+Math.random()*3})}}
loop(t){try{const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;this.update(dt);this.draw()}catch(err){console.error(err);this.toast('GAME ERROR — RELOAD',5000)}requestAnimationFrame(n=>this.loop(n))}
draw(){const c=this.ctx;c.fillStyle='#2a2524';c.fillRect(0,0,720,1120);this.drawWorld(c);for(const e of this.enemies)if(e.active)this.drawEnemy(c,e);for(const p of this.projectiles)if(p.active)this.drawProjectile(c,p);for(const t of this.towers)this.drawTower(c,t);for(const p of this.pads)if(!p.tower)this.drawPad(c,p);for(const q of this.particles){c.globalAlpha=Math.max(0,q.life*2.5);c.fillStyle=q.color;c.fillRect(q.x-q.size/2,q.y-q.size/2,q.size,q.size)}c.globalAlpha=1;for(const f of this.floaters){c.globalAlpha=Math.min(1,f.life*2);c.fillStyle=f.color;c.font='bold 20px Arial';c.textAlign='center';c.fillText(f.text,f.x,f.y)}c.globalAlpha=1;if(this.combo>=3&&this.phase==='wave'){c.fillStyle='#fff';c.strokeStyle='#19151a';c.lineWidth=5;c.font='900 28px Arial';c.textAlign='center';c.strokeText(`${this.combo}× COMBO`,360,150);c.fillText(`${this.combo}× COMBO`,360,150)}if(this.banner){c.globalAlpha=Math.min(1,this.banner.life*2);c.fillStyle=this.banner.color;c.strokeStyle='#251713';c.lineWidth=7;c.font='900 34px Arial';c.textAlign='center';c.strokeText(this.banner.text,360,560);c.fillText(this.banner.text,360,560);c.globalAlpha=1}}
drawWorld(c){const g=c.createLinearGradient(0,0,720,1120);g.addColorStop(0,'#49312d');g.addColorStop(.55,'#302b2c');g.addColorStop(1,'#1e2225');c.fillStyle=g;c.fillRect(0,0,720,1120);c.globalAlpha=.45;c.strokeStyle='#ff6a2a';c.lineWidth=5;for(const [x,y] of [[80,280],[220,470],[620,760],[130,1060],[570,1030]]){c.beginPath();c.moveTo(x-35,y);c.lineTo(x,y-18);c.lineTo(x+28,y+8);c.stroke()}c.globalAlpha=1;c.lineJoin='round';c.lineCap='round';c.strokeStyle='#15191c';c.lineWidth=62;c.beginPath();MAP.path.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.stroke();c.strokeStyle='#67615d';c.lineWidth=52;c.stroke();c.strokeStyle='#978e84';c.lineWidth=40;c.stroke();c.strokeStyle='#2b2a29';c.lineWidth=3;c.setLineDash([14,13]);c.stroke();c.setLineDash([]);this.drawFactory(c);this.drawBase(c)}
drawFactory(c){for(const [x,y] of [[80,170],[170,350],[650,900]]){c.fillStyle='#1b2024';c.fillRect(x-20,y-45,40,90);c.fillStyle='#ff6a2a';c.fillRect(x-13,y-34,26,12);c.fillStyle='#3c444a';c.fillRect(x-8,y-75,16,30)}c.fillStyle='#6b3a2b';for(const [x,y] of [[60,610],[680,720],[250,235]]){c.beginPath();c.arc(x,y,28,0,Math.PI*2);c.fill();c.fillStyle='#ff7438';c.beginPath();c.arc(x,y,13,0,Math.PI*2);c.fill();c.fillStyle='#6b3a2b'}}
drawBase(c){const{x,y}=MAP.base;c.save();c.translate(x,y);c.shadowColor='#0009';c.shadowBlur=14;c.shadowOffsetY=8;c.fillStyle='#182c3d';c.strokeStyle='#ff9b57';c.lineWidth=7;c.beginPath();c.arc(0,0,82,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#e7eef5';c.fillRect(-52,-46,104,92);c.fillStyle='#274b67';c.fillRect(-36,-30,72,60);c.fillStyle='#ff6f37';c.fillRect(-18,-14,36,28);c.fillStyle='#ffe0a8';c.fillRect(-8,-7,16,14);c.restore()}
drawPad(c,p){const price=TOWERS[p.type].cost,ok=this.gold>=price;c.save();c.translate(p.x,p.y);c.fillStyle='#12374c';c.strokeStyle=ok?'#72dcff':'#56616a';c.lineWidth=5;c.beginPath();c.arc(0,0,31,0,Math.PI*2);c.fill();c.stroke();c.fillStyle=ok?'#1c8ed1':'#46515a';c.fillRect(-38,-73,76,36);c.fillStyle='#ffd22b';c.beginPath();c.arc(-20,-55,9,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='bold 18px Arial';c.textAlign='center';c.fillText(price,11,-48);c.restore()}
drawTower(c,t){const s=t.stats;c.save();c.translate(t.x,t.y);c.fillStyle='#eaf4f8';c.strokeStyle=s.accent;c.lineWidth=5;c.beginPath();c.arc(0,0,28+t.level*2,0,Math.PI*2);c.fill();c.stroke();c.rotate(t.angle);c.fillStyle=s.accent;if(t.type==='gun')c.fillRect(-5,-6,34+t.level*3,12);else if(t.type==='cannon')c.fillRect(-3,-11,38+t.level*3,22);else{c.fillStyle='#8cefff';c.beginPath();c.arc(8,0,15+t.level,0,Math.PI*2);c.fill();c.fillStyle=s.accent;c.fillRect(5,-5,28+t.level*2,10)}c.restore();c.fillStyle='#fff';c.strokeStyle='#111';c.lineWidth=3;c.font='bold 11px Arial';c.textAlign='center';c.strokeText(`L${t.level}`,t.x,t.y+46);c.fillText(`L${t.level}`,t.x,t.y+46)}
drawEnemy(c,e){const ox=Math.cos(e.angle+Math.PI/2)*e.lane,oy=Math.sin(e.angle+Math.PI/2)*e.lane,x=e.x+ox,y=e.y+oy;c.save();c.translate(x,y);c.rotate(e.angle);if(e.type==='splitter'){c.fillStyle='#ff6f32';c.strokeStyle='#7b2c1d';c.lineWidth=3;c.beginPath();c.arc(0,0,e.size,0,Math.PI*2);c.fill();c.stroke();c.strokeStyle='#ffd17a';c.beginPath();c.moveTo(-8,-8);c.lineTo(8,8);c.moveTo(8,-8);c.lineTo(-8,8);c.stroke()}else if(e.type==='mite'){c.fillStyle=e.color;c.beginPath();c.arc(0,0,e.size,0,Math.PI*2);c.fill()}else if(e.type==='boss'){c.fillStyle='#a73729';c.strokeStyle='#ff9b57';c.lineWidth=5;c.beginPath();c.arc(0,0,e.size,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#ff6f37';c.fillRect(-20,-8,40,16);c.fillStyle='#ffd7a0';c.fillRect(8,-3,8,6)}else{c.fillStyle='#1c2b25';c.fillRect(-e.size*.7,e.size*.4,e.size*.45,e.size*.8);c.fillRect(e.size*.2,e.size*.4,e.size*.45,e.size*.8);c.fillStyle=e.color;c.strokeStyle='#173f2b';c.lineWidth=2;c.beginPath();c.arc(0,0,e.size,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#183c28';c.beginPath();c.arc(0,-e.size*.35,e.size*.82,Math.PI,0);c.fill()}c.restore();if(e.hp<e.maxHp){c.fillStyle='#221b1b';c.fillRect(x-14,y-e.size-10,28,4);c.fillStyle='#ff7a52';c.fillRect(x-14,y-e.size-10,28*Math.max(0,e.hp/e.maxHp),4)}}
drawProjectile(c,p){if(p.type==='gun'){c.strokeStyle='#dff7ff';c.lineWidth=3;c.beginPath();c.moveTo(p.px,p.py);c.lineTo(p.x,p.y);c.stroke()}else{c.fillStyle=p.type==='cannon'?'#ffb24b':'#bffcff';c.beginPath();c.arc(p.x,p.y,p.type==='cannon'?7:5,0,Math.PI*2);c.fill()}}
}
function boot(){try{new Game()}catch(err){console.error(err);document.body.innerHTML='<div style="color:white;padding:30px;font:20px system-ui">FUN TD failed to start. Please reload.</div>'}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();