(()=>{
const overlay=document.getElementById('warRoomOverlay'),open=document.getElementById('warRoomButton'),close=document.getElementById('warRoomClose');if(!overlay||!open)return;
const $=id=>document.getElementById(id),K='funTD_';
const get=(k,d=0)=>{const v=localStorage.getItem(K+k);return v==null?d:(Number.isFinite(+v)?+v:v)};const set=(k,v)=>localStorage.setItem(K+k,String(v));
const sectorStars=n=>+localStorage.getItem(`funTD_sector${n}Stars`)||0,sectorClear=n=>localStorage.getItem(`funTD_sector${n}Clear`)==='1';
const research={salvage:{name:'CORE SALVAGE',desc:'Earn +1 Tech Core per sector clear for each level.',max:3,base:8,icon:'◆'},medals:{name:'MEDAL ANALYSIS',desc:'Earn +1 Tech Core whenever you improve a sector medal, per level.',max:3,base:10,icon:'★'},efficiency:{name:'COMMAND EFFICIENCY',desc:'Reduce future War Room research costs by 5% per level.',max:3,base:12,icon:'⌁'},archive:{name:'ARCHIVE NETWORK',desc:'Expand boss intelligence and permanently increase dossier reward value.',max:3,base:9,icon:'▦'}};
function migrateRewards(){if(get('warRoomMigrated',0))return;let cores=0;for(let n=1;n<=3;n++){const s=sectorStars(n);cores+=s*3+(sectorClear(n)?5:0);set(`rewardedStars${n}`,s);set(`rewardedClear${n}`,sectorClear(n)?1:0)}set('cores',get('cores',0)+cores);set('warRoomMigrated',1);if(cores)set('coresEarned',get('coresEarned',0)+cores)}migrateRewards();
function lvl(id){return get(`research_${id}`,0)}function discount(){return 1-lvl('efficiency')*.05}function cost(id){const r=research[id],l=lvl(id);return Math.max(1,Math.round(r.base*(1+l*.75)*discount()))}function rank(){const spent=get('coresSpent',0);return spent>=100?['WAR COMMANDER',100,100]:spent>=60?['COLONEL',spent-60,40]:spent>=35?['MAJOR',spent-35,25]:spent>=18?['CAPTAIN',spent-18,17]:spent>=7?['LIEUTENANT',spent-7,11]:['RECRUIT',spent,7]}
function syncCampaignRewards(){for(let n=1;n<=3;n++){const s=sectorStars(n),prev=get(`rewardedStars${n}`,0);if(s>prev){const diff=s-prev,reward=diff*(3+lvl('medals'));set('cores',get('cores',0)+reward);set('coresEarned',get('coresEarned',0)+reward);set(`rewardedStars${n}`,s);set('medalUpgrades',get('medalUpgrades',0)+diff)}if(sectorClear(n)&&!get(`rewardedClear${n}`,0)){const reward=5+lvl('salvage');set('cores',get('cores',0)+reward);set('coresEarned',get('coresEarned',0)+reward);set(`rewardedClear${n}`,1)}}}
const achievements=[['first_clear','FIRST LINE HELD','Clear any campaign sector.','🏅',()=>[1,2,3].some(sectorClear)],['triple_star','PERFECT DEFENSE','Earn a 3-star sector medal.','★★★',()=>[1,2,3].some(n=>sectorStars(n)>=3)],['campaigner','THREE FRONTS','Clear all three current sectors.','🗺',()=>[1,2,3].every(sectorClear)],['builder','FORTIFICATION EXPERT','Build 50 towers across all runs.','⬡',()=>get('statBuilds',0)>=50],['engineer','FIELD ENGINEER','Perform 50 tower upgrades.','⚙',()=>get('statUpgrades',0)>=50],['exterminator','SWARM BREAKER','Destroy 1,000 enemies.','☠',()=>get('statKills',0)>=1000],['veteran','WAVE VETERAN','Start 100 waves.','⚔',()=>get('statWaves',0)>=100],['researcher','R&D ONLINE','Purchase your first War Room research level.','⌬',()=>get('coresSpent',0)>0]];
function updateAchievements(){for(const[a,,, ,test]of achievements)if(test())set(`achievement_${a}`,1)}
function render(){syncCampaignRewards();updateAchievements();const[rName,rNow,rNeed]=rank();$('warCores').textContent=get('cores',0);$('warRank').textContent=rName;$('warSpent').textContent=get('coresSpent',0);$('warRankFill').style.width=Math.min(100,rNeed?100*rNow/rNeed:100)+'%';
$('researchGrid').innerHTML=Object.entries(research).map(([id,r])=>{const l=lvl(id),max=l>=r.max,c=max?0:cost(id);return `<article class="research-card"><div class="achievement-icon">${r.icon}</div><h4>${r.name}</h4><p>${r.desc}</p><div class="research-meta"><span>LEVEL ${l}/${r.max}</span><span>${max?'MAX':c+' CORES'}</span></div><button data-research="${id}" ${max||get('cores',0)<c?'disabled':''}>${max?'MAXED':'RESEARCH'}</button></article>`}).join('');
overlay.querySelectorAll('[data-research]').forEach(b=>b.onclick=()=>buy(b.dataset.research));
$('achievementGrid').innerHTML=achievements.map(([id,name,desc,icon])=>{const yes=!!get(`achievement_${id}`,0);return `<article class="achievement-card ${yes?'unlocked':'locked'}"><div class="achievement-icon">${icon}</div><h4>${name}</h4><p>${desc}</p><strong>${yes?'UNLOCKED':'LOCKED'}</strong></article>`}).join('');
const bosses=[['SAND TITAN','Dustwall siege organism','☀',sectorClear(1)],['ICE TITAN','Frostline armored behemoth','❄',sectorClear(2)],['MAGMA COLOSSUS','Ashfall foundry war-machine','🔥',sectorClear(3)]];$('dossierGrid').innerHTML=bosses.map(([name,desc,icon,yes])=>`<article class="dossier-card ${yes?'':'locked'}"><div class="dossier-icon">${yes?icon:'?'} </div><h4>${yes?name:'CLASSIFIED'}</h4><p>${yes?desc:'Defeat the sector boss to unlock this dossier.'}</p></article>`).join('');
const totalStars=[1,2,3].reduce((a,n)=>a+sectorStars(n),0),clears=[1,2,3].filter(sectorClear).length;const stats=[['ENEMIES DESTROYED',get('statKills',0)],['TOWERS BUILT',get('statBuilds',0)],['UPGRADES',get('statUpgrades',0)],['WAVES STARTED',get('statWaves',0)],['SECTORS CLEARED',clears+'/3'],['CAMPAIGN STARS',totalStars+'/9'],['TECH CORES EARNED',get('coresEarned',0)],['TECH CORES SPENT',get('coresSpent',0)]];$('statsGrid').innerHTML=stats.map(([a,b])=>`<article class="stat-card"><strong>${b}</strong><span>${a}</span></article>`).join('')}
function buy(id){const r=research[id],l=lvl(id);if(!r||l>=r.max)return;const c=cost(id);if(get('cores',0)<c)return;set('cores',get('cores',0)-c);set('coresSpent',get('coresSpent',0)+c);set(`research_${id}`,l+1);updateAchievements();render()}
function show(){render();overlay.classList.add('show')}function hide(){overlay.classList.remove('show')}open.onclick=show;close?.addEventListener('click',hide);overlay.addEventListener('pointerdown',e=>{if(e.target===overlay)hide()});
overlay.querySelectorAll('[data-war-tab]').forEach(b=>b.onclick=()=>{overlay.querySelectorAll('[data-war-tab]').forEach(x=>x.classList.toggle('active',x===b));overlay.querySelectorAll('.war-panel').forEach(p=>p.classList.toggle('active',p.id===`war-${b.dataset.warTab}`))});
const start=$('startWave');start?.addEventListener('click',()=>set('statWaves',get('statWaves',0)+1));document.addEventListener('click',e=>{if(e.target.closest?.('[data-build]'))set('statBuilds',get('statBuilds',0)+1);if(e.target.closest?.('[data-up]'))set('statUpgrades',get('statUpgrades',0)+1)});
const prog=$('progressText');if(prog){let last=0;new MutationObserver(()=>{const now=parseInt((prog.textContent||'0').split('/')[0],10)||0;if(now>last)set('statKills',get('statKills',0)+(now-last));last=now}).observe(prog,{childList:true,subtree:true,characterData:true})}
const flowTitle=$('flowTitle');if(flowTitle)new MutationObserver(()=>{setTimeout(()=>{syncCampaignRewards();updateAchievements()},450)}).observe(flowTitle,{childList:true,subtree:true,characterData:true});
})();